### PR TITLE
fix process control in direct scheduler

### LINKED ISSUE #2649: retrieving files from completed calculation - file missing
While trying to move the `aiida-zeopp` to aiida 1.0, I have encountered a strange issue when  retrieving files back from a completed calculation using my plugin. 

I'm running the calculation with `run_get_node` and when the calculation finishes, it seems to me like this is happening (see logs below, I've added some extra prints here and there):
 * the first time it tries to retrieve the data, all output files are there except for one (`out.gridG`). I don't know why (I'm running a serial executable).
 * around 20s later, for some reason AiiDA tries again to retrieve the data; then all files are there

Is it possible that AiiDA's transport is somehow too quick for the file system?

I'm running on my local laptop using local transport and direct scheduler

```
03/26/2019 03:17:40 PM <6091> aiida.execmanager: [WARNING] Retrieving calc 85
03/26/2019 03:17:40 PM <6091> aiida.execmanager: [WARNING] try printing workdir
03/26/2019 03:17:40 PM <6091> aiida.execmanager: [WARNING] /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23
03/26/2019 03:17:40 PM <6091> aiida.execmanager: [WARNING] ['/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.cssr', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.res', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_scheduler-stderr.txt', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.volpo', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/MgO.cif', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.chan', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/MgO.rad', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_aiidasubmit.sh', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.vsa', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_scheduler-stdout.txt', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.strinfo', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.sa']
03/26/2019 03:17:40 PM <6091> aiida.execmanager: [DEBUG] [retrieval of calc 85] chdir /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] inside retrieving
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] ['out.cssr', 'out.res', 'out.sa', 'out.vsa', 'out.volpo', 'out.chan', 'out.strinfo', 'out.gridG', '_scheduler-stdout.txt', '_scheduler-stderr.txt']
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.cssr
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.cssr'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.res
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.res'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.sa
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.sa'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.vsa
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.vsa'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.volpo
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.volpo'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.chan
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.chan'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.strinfo
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.strinfo'
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmpykhgps44/out.gridG
03/26/2019 03:17:40 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.gridG'
03/26/2019 03:17:40 PM <6091> aiida.engine.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/transports.py", line 106, in request_transport
    yield transport_request.future
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/processes/calcjobs/tasks.py", line 238, in do_retrieve
    raise Return(execmanager.retrieve_calculation(node, transport, retrieved_temporary_folder))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/daemon/execmanager.py", line 267, in retrieve_calculation
    retrieve_files_from_list(calculation, transport, folder.abspath, retrieve_list)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/daemon/execmanager.py", line 469, in retrieve_files_from_list
    transport.get(rem, os.path.join(folder, loc))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/transports/plugins/local.py", line 474, in get
    raise IOError("The remote path {} does not exist".format(remotepath))
OSError: The remote path out.gridG does not exist

03/26/2019 03:17:40 PM <6091> aiida.engine.transports: [DEBUG] Transport request closing transport for AuthInfo for leopold.talirz@epfl.ch on localhost
03/26/2019 03:17:40 PM <6091> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_retrieve excepted, retrying after 20 seconds
Traceback (most recent call last):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/utils.py", line 175, in exponential_backoff_retry
    result = yield coro()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp_py3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp_py3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp_py3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/processes/calcjobs/tasks.py", line 238, in do_retrieve
    raise Return(execmanager.retrieve_calculation(node, transport, retrieved_temporary_folder))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/daemon/execmanager.py", line 267, in retrieve_calculation
    retrieve_files_from_list(calculation, transport, folder.abspath, retrieve_list)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/engine/daemon/execmanager.py", line 469, in retrieve_files_from_list
    transport.get(rem, os.path.join(folder, loc))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/transports/plugins/local.py", line 474, in get
    raise IOError("The remote path {} does not exist".format(remotepath))
OSError: The remote path out.gridG does not exist
03/26/2019 03:18:02 PM <6091> aiida.engine.transports: [DEBUG] Transport request opening transport for AuthInfo for leopold.talirz@epfl.ch on localhost
03/26/2019 03:18:02 PM <6091> aiida.engine.processes.calcjobs.tasks: [INFO] retrieving CalcJob<85>
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [WARNING] Retrieving calc 85
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [WARNING] try printing workdir
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [WARNING] /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [WARNING] ['/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.cssr', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.res', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_scheduler-stderr.txt', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.volpo', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/MgO.cif', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.chan', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.gridG', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/MgO.rad', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_aiidasubmit.sh', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.vsa', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/_scheduler-stdout.txt', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.strinfo', '/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23/out.sa']
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [DEBUG] [retrieval of calc 85] chdir /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/tmpbi_z_qlq/fe/b9/b75b-9260-4bb4-82cf-239fd77b9b23
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] inside retrieving
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] ['out.cssr', 'out.res', 'out.sa', 'out.vsa', 'out.volpo', 'out.chan', 'out.strinfo', 'out.gridG', '_scheduler-stdout.txt', '_scheduler-stderr.txt']
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.cssr
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.cssr'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.res
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.res'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.sa
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.sa'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.vsa
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.vsa'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.volpo
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.volpo'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.chan
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.chan'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.strinfo
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.strinfo'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/out.gridG
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item 'out.gridG'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/_scheduler-stdout.txt
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item '_scheduler-stdout.txt'
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/sandbox/tmp3rov2uv1/_scheduler-stderr.txt
03/26/2019 03:18:02 PM <6091> aiida.transport.LocalTransport: [WARNING] [retrieval of calc 85] Trying to retrieve remote item '_scheduler-stderr.txt'
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [DEBUG] [retrieval of calc 85] Storing retrieved_files=None
03/26/2019 03:18:02 PM <6091> aiida.engine.transports: [DEBUG] Transport request closing transport for AuthInfo for leopold.talirz@epfl.ch on localhost
03/26/2019 03:18:02 PM <6091> aiida.engine.processes.calcjobs.tasks: [INFO] retrieving CalcJob<85> successful
03/26/2019 03:18:02 PM <6091> aiida.engine.persistence: [DEBUG] Persisting process<85>
03/26/2019 03:18:02 PM <6091> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x117e53908>'
03/26/2019 03:18:02 PM <6091> aiida.execmanager: [DEBUG] [parsing of calc 85] Content of the retrieved_temporary_folder:

03/26/2019 03:18:02 PM <6091> aiida.parser.NetworkParser: [ERROR] ['_scheduler-stderr.txt', '_scheduler-stdout.txt', 'out.chan', 'out.cssr', 'out.gridG', 'out.res', 'out.sa', 'out.strinfo', 'out.volpo', 'out.vsa']
03/26/2019 03:18:02 PM <6091> aiida.parser.NetworkParser: [ERROR] /Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path
03/26/2019 03:18:02 PM <6091> aiida.parser.NetworkParser: [ERROR] retrieve list
03/26/2019 03:18:02 PM <6091> aiida.parser.NetworkParser: [ERROR] ['out.cssr', 'out.res', 'out.sa', 'out.vsa', 'out.volpo', 'out.chan', 'out.strinfo', 'out.gridG', '_scheduler-stdout.txt', '_scheduler-stderr.txt']
03/26/2019 03:18:02 PM <6091> aiida.parser.NetworkParser: [ERROR] ['/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.cssr', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.res', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/_scheduler-stderr.txt', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.volpo', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.chan', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.gridG', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.vsa', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/_scheduler-stdout.txt', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.strinfo', '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository/plugin_migration/repository/node/2c/fa/659c-3ad3-4ad4-8d06-3bf0816d56ae/path/out.sa']
03/26/2019 03:18:03 PM <6091> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x117e53908>'
```

### PR DESCRIPTION
**Pull request by ltalirz**
fix #2649 

The direct scheduler was using `ps` for checking whether a process is
running. However, `ps` does not show processes without a controlling
terminal - for this you need to add the -x option:

-x      When displaying processes matched by other options, include pro-
        cesses which do not have a controlling terminal.  This is the
        opposite of the -X option.  If both -X and -x are specified in
        the same command, then ps will use the one which was specified
        last.

### CODE REVIEW

**Comment by ltalirz** [comment]
What I haven't done here is add a test that would catch a regression.
I saw there were some tests in the schedulers/plugins directory but only related to parsing job lists.

Is there also an actual test of a scheduler?

**Comment by sphuber** [comment]
Why didn't this problem affect me on theossrv5? Is this behavior specific to MacOS or should it also affect Linux?

**Comment by giovannipizzi** [comment]
@sphuber I try to answer (with a few more questions) in the issue

**Comment by ltalirz** [comment]
@sphuber @giovannipizzi can this be merged?
this issue breaks my integration tests for two plugins...

**Comment by sphuber** [comment]
Could you please add a little bit more information to the comment you added at the `ps` command. Something that explains why we need to put `-x` and how it will manifest itself if we don't, i.e. the engine will think that the process is terminated when it is not and will start the retrieval step too early.

**Comment by ltalirz** [comment]
Done!

**Pull request merged**
