### PR TITLE
Fixes #722 issue affecting failed workflows

### LINKED ISSUE #722: WorkChains restart from first step when output doesn't match spec
The example below will print hello world over and over again:

`
class ZombieWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super(ExampleWC, cls).define(spec)
        spec.output('out', valid_type=NumericType)
        spec.outline(cls._step)

    def _step(self):
        print 'hello world'
`

### PR DESCRIPTION
**Pull request by muhrin**
We overwrote the constructor for Persistence but did not call the super
class.  This was a problem because the super constructor was actually
adding the class as a listener of the MONITOR.  It is the MONITOR that
would tell the persistence when a process had crashed (because of
exception).  This means that the pickle was not being moved to failed
and therefore the workflow would be re-ran.

### CODE REVIEW

**Comment by sphuber** [comment]
Martin! Good to hear from you mate. I am curious though, why did this not happen when I just ran the daemon as opposed to manually calling `tick_workflow_engine`?

**Comment by muhrin** [comment]
@sphuber I asked myself the same thing.  Turns out the bug was _sorta_ there with the daemon as well.  What would happen is that the `process` would crash but the flock would remain (because persistence hadn't received the message about it failing).  So the daemon wouldn't try to re-run it...until it was restarted.  So it's a little subtle to notice.

**Comment by sphuber** [comment]
Pulled the changes locally and the zombie test now runs as expected.

**Comment by lekah** [comment]
Thanks guys, it also works for me!

**Pull request merged**
