### PR TITLE
add note on updating reentry cache from python

### PR DESCRIPTION
**Pull request by ltalirz**
This issue was raised by @mottetm in an environment where the
user did not have access to the command line
https://github.com/DropD/reentry/issues/29

### CODE REVIEW

**Comment by sphuber** [comment]
We missed this one apparently. It doesn't look too urgent. Can this be rebased on develop?

**Comment by ltalirz** [comment]
yes, it's just the docs where people anyhow mainly look at develop

**Comment by sphuber** [comment]
Ok the automatic feature to change the base branch does not correctly resolve the commits, so could you please rebase manually on `develop` and just force push? Thanks

**Comment by ltalirz** [comment]
Closing in favor of #1669

**Pull request closed without merging**
