### PR TITLE
Serialize process inputs

### LINKED ISSUE #629: Automatically convert basic types to AiiDA types
When providing inputs to a ``WorkChain``, it would be nice if basic Python types (``int``, ``float``, etc.) converted to the corresponding AiIDA types automatically. A function that does this conversion is already implemented in ``data.base.to_aiida_type``. Maybe it would also be nice to make this configurable from the ``spec.input``, i.e. being able to provide a function which takes the input and converts it into an AiiDA type.

In terms of implementing this, the following would be a possible route: 
* add a keyword argument (``conversion_function``) to ``ProcessSpec.input``, which defaults to ``data.base.to_aiida_type`` (in AiiDA, not Plum)
* In ``Process.__init__``, apply the conversion functions to all inputs before anything else

What are your thoughts?

### PR DESCRIPTION
**Pull request by greschd**
Fixes #629.

Adds a ``serialize_fct`` keyword argument to the ``InputPort``, which can be used to specify a serialization function that is called if the input is not an AiiDA data type.

This is implemented by adding a ``serialize`` method to the ``InputPort`` and ``PortNamespace``, which takes an input / input dictionary and applies the serialization.

What's a bit ugly is that this method then needs to be called in several places:
- In the runners ``_create_inputs_dictionary`` method
- In the Process ``__init__``
- In the ``submit`` free function, via ``_create_inputs_dictionary``

because I didn't find an easy place to put it where it would always be called _before_ the input nodes are stored. Suggestions for improving this are very welcome.

Side note: In ``rmq.py``, I changed it from using ``json`` to ``yaml``, because otherwise the raw input cannot be processed.

To-Do: 
- [x] Documentation

P.S.: In the daemon test, I noticed that a top-level ``submit`` call can take quite a while to return -- is that expected?

### CODE REVIEW

**Comment by sphuber** [comment]
On your last post scriptum: yes, we wanted the function to return a `pk` corresponding to the node that was created, such that the user has a handle to query it through `verdi`. However, all the `submit` call does is send a `launch` request over RabbitMQ. So if we want the `pk` back, we need to wait for the `ProcessLauncher` to pick up the message, instantiate the process, submit a `ContinuationTask` and send confirmation of the launch with the pk. This whole process is the delay that you are seeing

**Comment by greschd** [comment]
Alright, I just wanted to make sure it's not a problem with the serialization itself.

**Comment by greschd** [comment]
Blocked by #1243.

**Comment by sphuber** [comment]
I just noticed this was automatically closed because I deleted the `workflows` branch. This was not to say that I think it should not be merged

**Comment by giovannipizzi** [comment]
maybe @greschd then should rebase on develop and reopen it/open a new one?

**Comment by greschd** [comment]
Ah just realized it's quite messed up now. I'll open up a different PR with the changes cherry-picked.

**Pull request closed without merging**
