### PR TITLE
add instructions when verdi import fails

### PR DESCRIPTION
**Pull request by ltalirz**
* when verdi import fails because of an old/new export file version, add a hint on what to do
 * fix issue with pip 19.x
 * fix issue with prospector failing to install
 * fix nasty travis issue with build of pymatgen (built using incompatible numpy version provided by travis)

### CODE REVIEW

**Comment by ltalirz** [comment]
@giovannipizzi I've already fixed two issues that prevented `release_v0.12.3` from building but now I'm stuck with [this numpy/pymatgen issue](https://travis-ci.org/aiidateam/aiida_core/jobs/484118665#L1450)

I'm a bit puzzled because, originally, both the numpy version and the pymatgen version were the same as in `provenance_redesign` (also the `cython` build requirement I only added afterwards, trying to fix the issue). 
Any ideas what could be causing this?

**Comment by giovannipizzi** [comment]
did you try `pip<19` instead of pip 19 with `--no-use-pep517`? Maybe the way things are done in pip 19 are different

**Comment by ltalirz** [comment]
I'm unable to reproduce the problem locally in a conda environment with python 2.7
```
pip install --upgrade pip
pip install pymatgen==2018.12.12 numpy==1.15.4 scipy==1.1.0
python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.util import coord_cython
>>>
```

**Comment by giovannipizzi** [comment]
Try to delete the travis cache, it is possible that it's using a cached version? From the travis GUI you should have a button to clear the cache for this specific PR/branch

**Comment by ltalirz** [comment]
Ok, just for the record: adding numpy==1.15.4 as build dependency did *not* solve the problem.
Now deleted the cache for the PR and restarted the job...

**Comment by giovannipizzi** [comment]
Did you clear it for the correct branch/PR? Also, if the cache is missing, I don't know if it reuses the cache of the source branch (in your fork) and/or the destination branch, you might want to try cleaning up those as well and rebuilding with `-vvv`?

**Comment by ltalirz** [comment]
yeah, I was wondering that - looking back at the travis job I thought I restarted, it looks to me like it was still using the cache.
Restarting this job now: https://travis-ci.org/aiidateam/aiida_core/jobs/485255224 let's see...

**Comment by ltalirz** [comment]
It seems since the previous job was terminated too early, pymatgen was downloaded again now (this differs from the usual output before):
```
Collecting pymatgen==2018.12.12 (from aiida-core==0.12.2)
  Downloading https://files.pythonhosted.org/packages/d6/b9/f386300f232c8523f562e39bf07bae0d9c4e6379f423f71df7cd622ddae7/pymatgen-2018.12.12.tar.gz (2.0MB)
...
 Running setup.py bdist_wheel for pymatgen ... \|/-\||done
  Stored in directory: /home/travis/.cache/pip/wheels/4e/8c/1e/41c73592a64ed7e1f7bf5e52f9009eb9987b753d0a128226b3
```
I uncommented the uninstallation of numpy, so the upgrade from numpy 1.13 to 1.15 happens only at the very end (the numpy 1.15.4 specified in the `pyproject.toml` should mean, however, that this numpy is seen during build).

However, now that we know a wheel is being downloaded I believe it doesn't matter at all what version of numpy we have - it matters what they had when they compiled the binary for the wheel.

I see two possible ways forward:
 * try to match their build environment (it might, however, be that they simply ran on a different architecture(?) )
 * disable build of the wheels.

Finally, there is still the mystery why PRs to `provenance_redesign` are able to build...
it seems like I'm overlooking something.

**Comment by ltalirz** [comment]
Looks like this indeed fixed the issue - yay!

To summarize:
 * travis is downloading a source package of pymatgen (file ending in `.tar.gz`), then runs `python setup.py bdist_wheel` and stores the wheel in the travis cache, which is reused from the next build on
 * by default, the travis python environment has numpy 1.13.3 installed which causes the error
   > numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
  
   when running the aiida test suite with the correct numpy version 1.15.4 for pymatgen 2018.12.12

This remains a mystery to me:
 * for some reason, adding `numpy==1.15.4` to the `build-system` in  `pyproject.toml` has no effect. I haven't been able to spot any typos.

 * I still don't understand how builds on PRs to `provenance_redesign` are working - I've checked the .travis.yml and could not identify at which point it might lead to a different environment/numpy version for python 2.7

**Comment by sphuber** [comment]
Regarding the question why builds are working for `provenance_redesign`, I think I encountered a similar/related issue at some point with builds failing, due to a mismatch between `numpy` and `scipy` at the time. I also tracked it down to a wrong version of `numpy` being built from the cache on Travis, [so I added a `--no-cache-dir` flag which seemed to work](https://github.com/aiidateam/aiida_core/commit/0b78a3d9742ddf36c68939dd413214800ebeb03d). Note that it is still there now and is probably sub optimal and we should maybe remove it

**Comment by ltalirz** [comment]
Thanks @sphuber - that does indeed explain it.

> Note that it is still there now and is probably sub optimal and we should maybe remove it

Hm... I guess it will make builds longer. On the other hand, perhaps it is the only way to make the `pyproject.toml` work on travis?

**Comment by ltalirz** [comment]
Just to add another chapter to the story - I had a documentation build fail because pymatgen was installing a 1.17.0rc1 version of numpy (no idea how pip got the idea that it should be allowed to install release candidates):
https://travis-ci.org/ltalirz/aiida_core/jobs/553536605#L998

Apparently, this version of numpy requires python >= 3.5, so the build failed there.

Note: I guess some of the issue comes from the fact that pymatgen [specifies `numpy>=1.14` in the `setup_requires`](https://github.com/materialsproject/pymatgen/blob/master/setup.py#L91), which may make the build non-deterministic (and I don't know whether there is any way of controlling from the "outside" which version of numpy is installed inside the build environment).

**Comment by sphuber** [comment]
I have the same problem now on all my branches on my fork. All my py2.7 tests are failing. The weird thing is that we explicitly specify `numpy==1.16.1` in our `setup.json` but apparently this gets overridden by the requirement of pymatgen. I think this should be considered a bug in `pip`. The requirements  `numpy==1.16.1` and `numpy>=1.14` are *not* in conflict and what's more, `pip` should not be installing `1.17.0rc1` to begin with, since it is a pre-release

**Comment by sphuber** [comment]
The problem seems to be that `setup_requires` is not actually handled by `pip`, but rather by `easy_install` so our requirements are ignored. I have looked around but so far cannot find anyway to force a limit on the `setup_requires` dependencies of a dependency. What a mes...

**Pull request merged**
