### PR TITLE
Fix #658 - process pickles not being locked

### LINKED ISSUE #658: WorkChain step which takes a long time is executed multiple times
Measurements from a simple WorkChain with two steps, each submitting one calculation. Timeout in the first step.

Timout (s) | \# instances first step | \# instances second step
--|--|--
20 | 5 | 1
40 | 8 | 1
60 | 8 | 2

* Only ``submit`` is affected, not ``run``.
* Going back to ``0c407604b8f255946`` does not fix the issue.
* The step itself is executed multiple times (writes the ``report`` messages etc.), not just the calculation it spawns.

### PR DESCRIPTION
**Pull request by sphuber**
The majority of this should really go in `plum`. For now we have just implemented it in the `Persistence` class of `aiida` as to not have to create another `plum` support release. In the new release that is coming up, these changes should be contained within `plum`.

### CODE REVIEW

**Comment by sphuber** [comment]
Note: do not merge yet. Running extensive integration tests shows that something is still wrong

**Comment by greschd** [comment]
When this is fixed, I'm guessing we should cherry-pick the commits to ``master`` and create a bugfix release, right?

**Comment by sphuber** [comment]
You mean 'if' this is fixed... :S 
But yeah you're right, I think this is serious enough to deserve a bugfix release.

**Comment by sphuber** [comment]
This should now have fixed the original issue. @greschd if you could verify this PR solves the issue for your test, then we can hopefully merge this PR

**Comment by greschd** [comment]
This does indeed solve the issue for my test. Nice work :+1:

**Pull request merged**
