### PR TITLE
travis: fix pgtest failure

### PR DESCRIPTION
**Pull request by dev-zero**
Based on https://github.com/travis-ci/travis-ci/issues/9011 it seems we
have to specify explicitly the dependency on the postgresql-dev package
by now.

### CODE REVIEW

**Comment by dev-zero** [comment]
ok, now `pgtest` is unable to start the postgresql server in time (timeout)

**Comment by DropD** [comment]
5 s should be ample time for postgres to start, there might be something preventing the server from starting.

**Comment by dev-zero** [comment]
a debug build in travis shows the following entries when running pgtest's locate command to find the `pg_ctl` command:

```
$ locate -r '/pg_ctl$'
/usr/lib/postgresql/9.2/bin/pg_ctl
/usr/lib/postgresql/9.3/bin/pg_ctl
/usr/lib/postgresql/9.4/bin/pg_ctl
/usr/lib/postgresql/9.5/bin/pg_ctl
/usr/lib/postgresql/9.6/bin/pg_ctl
```

**Comment by dev-zero** [comment]
@DropD thanks, I noticed. Can you review the changes? It seems that the issue was that `locate` inside `pgtest` was actually picking up PostgreSQL-9.2. Commit 030e716 solves an unrelated issue I encountered when setting up a private Travis instance to get into the debug mode. There a SSH-Key was already available, but with its public key only in `authorized_keys` instead of a separate `id_rsa.pub` file. Not sure whether it was because of the debug mode, the private instance or a caching issue.

**Comment by DropD** [comment]
@dev-zero can you please make a pull request with the same changes to `release_v0.12.2`?

**Comment by dev-zero** [comment]
@DropD np, sure, see PR #1736

**Pull request merged**
