### PR TITLE
CifData: fast scanning and lazy parsing

### LINKED ISSUE #1183: fast CIF file parsing
I've just benchmarked the speed of parsing large CIF files (several hundreds of atoms each) into python representations with ASE, pymatgen and PyCifRW.
From my findings, by default ASE and PyCifRW are about on par (pymatgen is 2x slower). 
However, using `scan_type='flex'` in PyCifRW results in another 4x speedup.

All one needs to do is to replace
https://github.com/aiidateam/aiida_core/blob/62a5258f09d92dd36cd75f5f462196c24037b078/aiida/orm/data/cif.py#L494
by `c = CifFile.ReadCif(self.get_file_abs_path(), scan_type='flex')`

The documentation of PyCifRW says 
> `flex`  will tokenise the input CIF file using fast C routines, but is not available for CIF2/STAR2 files.

so I'm not sure it is the best choice for everyone, but I would definitely want to use it.

In my view, this should be an aiida-wide setting. Can someone tell me where I should put it?

### LINKED ISSUE #1186: CifData constructor parses cif file, and then throws parsed object away
In the following piece of code
```
from aiida.data.orm.cif import CifData
a = CifData(file="/path/to/file.cif")
```
the constructor of CifData seems to first parse the CIF file, and then throw the information away again.

Below is the code for the constructor:
https://github.com/aiidateam/aiida_core/blob/62a5258f09d92dd36cd75f5f462196c24037b078/aiida/orm/data/cif.py#L513-L519
After line 517, `self._values` actually holds the parsed CIF object [1]. Then it is set to `None`.

This raises a few questions
1. Is this a bug or am I missing something?
1. Regardless of whether it is intentional or not, in my opinion the code needs to change, as it is very difficult to understand what is going on under the hood. This could be done either by changing some of the node-level logic that causes the `_values` to be set (which I would prefer) or by *hiding* the `_values` from this logic. Which of the two routes should be followed?
1. I think for `CifData` in the end one wants at least two options for the constructor: a *direct* one, where the constructor parses the contents of the cif file and stores them, and a *lazy* one, where the constructor just stores the file name and the Cif file is parsed on demand.
  Perhaps even a third one, which is the current model of storing only formula & spacegroup and throwing away the python object so that it does not bloat the DB.
  Which of these options should be the default?

Mentioning @merkys who seems to have written these lines...
Also mentioning @giovannipizzi @nmounet 

[1] This goes via a rather complicated route. The `super` calls
aiida/orm/implementation/sqlalchemy/node.py `_init__`
=> aiida/orm/implementation/general/node.py `_set_with_defaults`
=> aiida/orm/implementation/general/node.py `_set_internal`
=> (somehow) aiida/orm/data/cif.py `set_file`
=> aiida/orm/data/cif.py `_set_attr('formulae', self.get_formulae())`
which causes the CIF file to be read

**Edit:** Regarding 2., on reflection it is not that strange anymore, if one has learned that in the 'AiiDA way' calling the constructor with  `file=<filename>` calls the `set_file` function
https://github.com/aiidateam/aiida_core/blob/62a5258f09d92dd36cd75f5f462196c24037b078/aiida/orm/data/cif.py#L528-L543
where `get_formula` then inevitably forces the parsing of the cif file.

### PR DESCRIPTION
**Pull request by ltalirz**
Fix #1183 
Fix #1186 

### Fast scanning
Adds a `scan_type` attribute to CifData.
Using `scan_type='flex'` uses C-routines of PyCifRW and is several times faster than the python-based implementation for large CIF files.
The default behavior is unchanged.

Example:
```
from aiida.orm.data.cif import CifData
a = CifData('/path/to/file.cif', scan_type='flex')
```

### Lazy parsing
Adds a `parse_policy` attribute to CifData.
Using `parse_policy='lazy'` delays parsing of CIF files until the values are actually needed.
The default behavior is unchanged, except for the fact that the CIF object is now kept in memory after regular parsing (see #1186)  (it will, however, not be written to the DB).

Example:
```
from aiida.orm.data.cif import CifData
a = CifData('/path/to/file.cif', parse_policy='lazy')
```

**Note:** 1st commit contains changes from formatter & linter

### CODE REVIEW

**Comment by ltalirz** [comment]
One change is that the calls to `get_formula` and `get_spacegroup_numbers` have moved from `set_file` into the constructor.
This means, the behavior of `a = CifData('/path/to/file.cif'` remains the same, but the behavior of
`a.set_file('/path/to/file.cif')` changes.

The reason for this change is that otherwise one needs to start fighting against the "cleverness" of AiiDA, which calls all the `set_...` functions in the constructor of the base class (e.g. one would need to make sure that `set_parse_policy` to be set *before* `set_file`).

I'll add something to `set_file` in order to prevent inconsistencies.

**Comment by ltalirz** [comment]
Closing this PR until convergence reached.

**Comment by ltalirz** [comment]
@giovannipizzi Feedback appreciated :-) You are also welcome to assign someone else, if you don't have the time.

**Comment by ltalirz** [comment]
@nmounet If you are not available, please unassign yourself and I will ask someone else.

**Comment by ltalirz** [comment]
@giovannipizzi It seems the Nicolas currently has no time.
Should we go ahead with this? I'm happy to add a bit of documentation here as well, if we agree on the implementation.

**Comment by giovannipizzi** [comment]
Do you know why tests are failing? (Probably when you'll fix them I have to approve again)

**Comment by ltalirz** [comment]
Yes... I removed the `main_file_name` argument of `_prepare_cif` because it is not used (the function just returns the cif string).
Now I see that there are many similar functions like this... I guess removing it is the right thing to do, but it might break other code...

**Pull request merged**
