### PR TITLE
Import JobCalculation from aiida.orm in ProcessRegistry

### PR DESCRIPTION
**Pull request by greschd**
Since the ``aiida.orm.calculation.job.JobCalculation`` is a subclass of ``aiida.orm.JobCalculation``, this makes the check for ``isinstance`` more generic.

### CODE REVIEW

**Comment by greschd** [comment]
It seems to me that ``from aiida.orm import JobCalculation`` should actually import ``aiida.orm.calculation.job.JobCalculation``, since it has the common code, additionally to the implementation-specific code. This would mean the import order in ``aiida/orm/__init__.py`` needs to be changed.

However, I'm not sure if that's how you want it to be done, or if usually it should actually be the implementation class which inherits from the generic class.

**Comment by DropD** [comment]
I feel the difference between `aiida.orm.calculation.job.JobCalculation` and `aiida.orm.JobCalculation` needs some clarification. For instance, right now builtin plugins derive from the former, while the plugins documentation recommends the latter.

Which is correct?

**Comment by greschd** [comment]
I don't really see why there is a separate class in ``aiida/orm/calculation/job/__init__.py``. It's docstring is ``"""Here I put all the attributes/method that are common to all backends"""`` -- but isn't that what is done in the ``AbstractJobCalculation``?

**Comment by greschd** [comment]
That is to say, I agree with @DropD that the distinction between the two imports (if there should be any at all) needs to be made clear. If there is no reason to distinguish the two, it should import the same class.

**Comment by giovannipizzi** [comment]
I think the double class is a mistake. The only method should be moved to the main class, and in aiida.orm.JobCalculation there should just be an import of the same class to simplify loading for the user, but the class should be the same. 
If you update the PR with this change, I think it can be merged. Thanks!

**Comment by greschd** [comment]
Okay, I updated the PR by de-duplicating the two classes, and moving the ``get_desc`` function to ``AbstractJobCalculation``.

**Pull request merged**
