### PR TITLE
fix subclass check in `existing calculations` test

### LINKED ISSUE #692: plugin backend test is subclass checking against the wrong JobCalculation class
When running tests locally with the `aiida-vasp` plugin installed,

```bash
verdi devel tests db.pluginloader
```

would fail due to plugin classes not being subclasses of JobCalculation.

It seems to be because the test imports

```python
from aiida.orm.calculation.job import JobCalculation
```

### PR DESCRIPTION
**Pull request by DropD**
fix #692

### CODE REVIEW

**Comment by szoupanos** [comment]
Rico, should I assume that this did not fail on Travis because we didn't have any plugins installed? I assume that the plugin loader worked correctly, even if the test failed. 

But does it make sense to have such a test without even a (dummy) plug-in?

**Comment by DropD** [comment]
It does make sense because 
* The test did not fail because the subclass check worked on the built in plugin classes (presumably they are subclasses of `aiida.orm.calculation.job.JobCalculation`
* The documentation states plugin calculations should be derived from `aiida.orm.JobCalculation`, therefore the test failed on external plugins.
* The test is worth keeping around because it has already caught some import errors on builtin plugins.

If indeed the check was correct, we need to update the documentation to recommend subclassing `aiida.orm.calculation.job.JobCalculation`

**Comment by DropD** [comment]
I forgot to mention that there are indeed included caclulation plugins like `simple.templatereplacer` already

**Comment by szoupanos** [comment]
OK, I see. So, it will fail if someone has an external plugin and it is not sub-classed as we propose in the documentation.

Fine with me.

**Pull request merged**
