### PR TITLE
Broeder j fix issue 638

### PR DESCRIPTION
**Pull request by broeder-j**
please check if this should be done this way or another way.

### CODE REVIEW

**Comment by broeder-j** [comment]
or why was super()._setup_db_records not called and code doubled? Not possible?

**Comment by broeder-j** [comment]
the other commit fixes issue 331

**Comment by broeder-j** [comment]
Do not merge yet. I have tried some simple JobCalcProcesses. in work chains I get some collisions with queue up,  _jobs_store... until I figure out why.

**Comment by sphuber** [comment]
The code you added to `JobCalculation._setup_db_record` should indeed be the solution to the problem. This method does not call the `super` for a reason like you suspected, because the super sets up the links which for the `JobCalculation` will already have been done. It is a bit of a hack.

Note that your commit also contains changes in an unrelated file. Those will have to be removed.

Maybe you can add some tests that run a simple `JobCalculation` setting the label and check that the calculation node will have them properly set.

**Comment by broeder-j** [comment]
Done. I forgot about those. I then commit these in an other pull request.  They fix issue 331.

Do you see anything else missing in ``JobCalculation._setup_db_record``?

**Comment by broeder-j** [comment]
From what I see, there are no unit tests for any work stuff, only in examples some non automated stuff, or? I can create a 'submission' type test. If this is what you want.

**Comment by sphuber** [comment]
There are unit tests in `aiida.backends.test.work`

**Comment by sphuber** [comment]
I have written a test that failed before adding the fix and succeeds after adding the code snippet to the `JobProcess._setupd_db_record`. What would be best way to get that into your PR?

**Comment by sphuber** [comment]
The tests failed because of an import error. My test file did not use `PwCalculation` but `TemplatereplacerCalculation`. Anyway, you can add the relevant import `from aiida.orm.calculation.job.simpleplugins.templatereplacer import TemplatereplacerCalculation` or just replace the `TemplatereplacerCalculation` with `PwCalculation`. In the latter case, maybe first run the tests locally to see if it works for a `PwCalculation`

**Comment by sphuber** [comment]
The tests are failing because the process of the test we added is still attached to the monitor. Could you try adding the following lines at the end of the test:

    job_instance.destroy()
    job_instance.run_until_complete()

and run the tests locally to see if that works.

**Comment by broeder-j** [comment]
still have to test locally.

**Comment by sphuber** [comment]
Tests were still failing, so I fixed the code locally and merged it in another PR #647
Hope you don't mind. But this one can now be closed

**Pull request closed without merging**
