### PR TITLE
FIX #723: clean_value more sensibly

### PR DESCRIPTION
**Pull request by ltalirz**
instead of calling `clean_value` every time one does `_set_attr`,
call it only when actually `store`ing data in the db.

This addresses issue #732 .

I'm not an expert in the aiida orm, so this will need **careful review**.
One question in particular: Am I right that `clean_value` isn't needed in `_set_db_extra` since 
 extras are anyhow not going to be stored? I might be wrong.

### CODE REVIEW

**Comment by giovannipizzi** [comment]
Can you add a test in 'db.nodes' that tries to set an attribute to something unstorable (e.g. an object) and verify that you catch the exception you expect? Another comment would be to try to run clean_value before you start the transaction, as this is potentially stopping and you want to stop as early as possible.

**Comment by ltalirz** [comment]
So, there are still some of the original tests failing which test what happens when you use `set_attr` and `set_extras` together with aiida basetypes.

It isn't quite clear to me what we actually want to happen.
In the naive implementation, `get_attr` will now simply return what you have put into `set_attr`.
But using `set_extra` and `get_extra` will return something different as it goes via the db (? still a bit confused about these extras...).

I'm not the person to decide these issues, so let me know what the desired behavior is.

**Comment by giovannipizzi** [comment]
Yes, in any case the DB can store only a subselection of types (e.g. tuples are converted to lists etc.).
Before the clean_value function was normalising the input before setting it, so even without storing the output was the same. Now, this is not the case anymore, which can be a bit confusing (but maybe if there is no other way, it's ok?).

BTW, extras are like attributes, with the differences that attributes define the content of the node, can be set (via a cache) before storing, and cannot change anymore afterwards (except fo a few exceptions, listed in the class). Instead extras can be set ONLY after storing, so go directly to the DB, and can be changed any time. They can be used by users to 'flag' nodes for faster querying.

**Comment by ltalirz** [comment]
Will reopen, once progress has been made.

**Comment by ltalirz** [comment]
The most important change is that we now have a `_append_to_attr` function that cleans only the object that is appended to.
I've started adding some tests, let me know if more tests are needed.
Furthermore, so far I'm using the new functionality only in StructureData. Other parts of aiida might benefit from it as well.

**Pull request merged**
