### PR TITLE
[WIP] Fix the broken celery logging

### LINKED ISSUE #943: Logging to celery log is broken
In the current `develop` branch, I am no longer seeing any of the report logs coming from running workchains in the daemon log. When a `WorkChain` calls `report`, it fires a message to the attached logger, which triggers the `DbLogHandler` causing it to end up in the database. These messages still show up just fine. However, I also used to see these messages in the normal daemon log. Those are now no longer there. What I do see frequently are errors like the following:

```
[2017-11-21 11:44:06,559: WARNING/Worker-6] Traceback (most recent call last):
[2017-11-21 11:44:06,559: WARNING/Worker-6] File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
[2017-11-21 11:44:06,559: WARNING/Worker-6] stream.write(fs % msg)
[2017-11-21 11:44:06,559: WARNING/Worker-6] IOError: [Errno 32] Broken pipe
[2017-11-21 11:44:06,559: WARNING/Worker-6] Logged from file log.py, line 282
```

I think these occur roughly when the workchains fire a report, so I think the two are related but I am not sure.

### PR DESCRIPTION
**Pull request by sphuber**
Fix #943 

Reconfigure the logging for each periodic celery task

This is an attempted solution to fix the broken pipe errors
in the celery worker logging. It probably is not the correct
way of solving it and is merely patching the result of an
incorrect configuration elsewhere.

The logging for AiiDA is configured from a dictionary in
`aiida/__init__.py`, where for the 'aiida' loggers and all its
children a database and console handler are configured. The
console handler is set to print to stdout. Once this logger is
triggered in the code executed by one of the celery workers of
the daemon process, the pipe to this file descriptor is broken
and an `IOError` exception is thrown.

The botch in this commit, reconfigures the logging at each task
call, which ensures that the file descriptor of the `StreamHandler`
is pointing to the correct stdout of the worker.

### CODE REVIEW

**Comment by sphuber** [comment]
I would definitely not merge this yet. I just wanted to open a PR so we can have a discussion. I am pretty sure that ultimately this is not the correct solution and I am merely triaging the underlying problem. If you don't have an idea let's indeed wait to discuss with the others first.

**Comment by giovannipizzi** [comment]
If this works, I would merge this for the time being, at least it alleviates the problem.
The dictionary was (at least in the Django case, and if things did not change) used by Django to setup the loggers. I don't remember what happened in the case of SQLA. If I understand correctly, even if the call to setup the loggers is called multiple times, it is not a problem, so even if the logging is also set up elsewhere, this should be ok.

If you agree with this view, feel free to merge this PR.

**Comment by sphuber** [comment]
It "works" but not as intended I presume. The logged messages now do show up in the daemon's logfile `celery.log`, however, they all have the format that the celery logger sets up and so all messages will be prefixed with `WARNING` even though the original level would be different. Example:

```
[2018-01-05 10:21:20,241: WARNING/Worker-5] 01/05/2018 10:21:20 AM, aiida.parser.PwParser: [ERROR] The xml output file 'data-file.xml' was not found but is required
```

I am not sure this actually fixes the real issue. See for example a potentially other related issue #1006

**Comment by sphuber** [comment]
@greschd This should now fix the issue of logging. If you have the time and interest, maybe you could run this PR against your workchains and see if you can reproduce it. Of course given that it was difficult to reproduce to begin with I am not sure how useful this is :smile:

**Pull request merged**
