### PR TITLE
Update reentry to v1.2.0 for release branch

### LINKED ISSUE #1429: Plugins are not properly registered upon installation with recent reentry
Recently there were some changes to `reentry` and the tests started failing. Specifically during the setup of the computer. It failed with the message that the transport is invalid. I put a print of the registered transport plugins just before the setup and sure enough it is empty. The reentry scan is apparently not working properly anymore.

With the alpha release of `v1.2.0` available we can test that it works in all relevant environments:

- [x] Travis `workflows`
- [x] Travis `release_v0.12.0`
- [x] Ubuntu clean virtual env `workflows`
- [x] Ubuntu clean virtual env `release_v0.12.0`
- [x] Mac OS X clean virtual env `workflows`
- [x] Mac OS X clean virtual env `release_v0.12.0`
- [ ] Conda `workflows`
- [x] Conda `release_v0.12.0`

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #1429 

Update reentry to v1.2.0 which fixes the issue with entry points not being registered.
This currently contains the alpha release `v1.2.0a9`, but once it is confirmed to work
in all relevant environments and branches the actual version `v1.2.0` will be released
and I will update this PR with the actual release

### CODE REVIEW

**Comment by sphuber** [comment]
I can temporarily lift the setting that rebasing or adding more commits renders the approval stale, so then reapproval is not necessary. Regarding the `REENTRY_PINNED` variable, that is something I think @giovannipizzi request so you would have to take that up with him

**Comment by ltalirz** [comment]
@sphuber Rico asked me to check out reentry with conda a few hours ago and it seemed to work (i.e. data plugin registered by aiida-siesta became available after `pip install aiida-siesta`).
This is on `release_v0.12.0`. I have no reason to believe that anything would change on `workflows`.

**Comment by giovannipizzi** [comment]
I asked for the REENTRY_PINNED variable (or any equivalent mechanism) because the version of reentry has to be specified in two different locations. It has nothing to do with this issue, so I would advise to keep it. @sphuber did you have a chance to check if this fixes also the Workflows branch?

**Comment by sphuber** [comment]
@giovannipizzi yes, you can check the issue #1429 where I added a list of checkboxes of environments that I have tested. We are just missing the check for both branches on Mac OS X. Could you maybe give a quick look to that on your machine?

**Pull request merged**
