### PR TITLE
fix #1041 update spinx-rtd scheme

### LINKED ISSUE #1041: documentation: line numbers in code-blocks don't match actual lines
Example: Search for "Here is the code:" on http://aiida-core.readthedocs.io/en/latest/work/index.html

This is a known bug in sphinx_rtd_theme, which has been fixed in v0.2.5
https://github.com/rtfd/sphinx_rtd_theme/issues/415

To do: Update `setup_requirements.py` accordingly and check that the problem is gone.

### PR DESCRIPTION
**Pull request by ltalirz**
This fixes an issue with line numbers not being displayed correctly.
(worked in docs created locally, but still broken on the web: Example: Search for "Here is the code:" on http://aiida-core.readthedocs.io/en/latest/work/index.html )

 * update sphinx rtd theme also for read-the-docs documentation
 * update python script for updating reqs

### CODE REVIEW

**Comment by sphuber** [comment]
Thanks Leopold for looking at this. Since the previous PR that addressed this issue was merged into `release_v0.11.0` could you please rebase your branch on `release_v0.11.1`. That way it will be fixed in the next patch release

**Comment by ltalirz** [comment]
@sphuber The reason this was branched off develop is that the documentation on RTD is build on develop. http://aiida-core.readthedocs.io/en/latest/
That's correct isn't it?

**Comment by sphuber** [comment]
Yes I guess that's true, but the release branch will be merged into `develop` once it is released. I am not sure if it is nice to also have it fixed in the release branch already. If not then I guess we can just merge into `develop` straight away

**Comment by ltalirz** [comment]
Well, the only point where this shows up is on RTD and I would rather have the 'latest' docs (which everyone reads) fixed now than the 0.11.1 + latest docs fixed whenever 0.11.1 is released.

**Pull request merged**
