### PR TITLE
Inherit inputs in WorkChain

### PR DESCRIPTION
**Pull request by greschd**
This is a proposal for a functionality that we briefly discussed at the last MARVEL meeting. 

The goal is to have an easy way to combine small workflows, by having a "wrapping" workflow that just consecutively calls the smaller workflows. The input to the smaller workflows needs to somehow be passed through the "wrapping" workflow, which results in code duplication when defining the specs.

This proposal implements two things:
* A method ``inherit_inputs`` on the ``ProcessSpec``, which takes a ``Process`` and adds its inputs to the current spec.
    * an optional keyword argument ``exclude`` to not inherit some input parameters. This can be used if some of the inputs are injected by the "wrapping" process.
* A method ``inherited_inputs`` of ``Process``, which again takes a ``Process``, and returns the (evaluated) inputs which were inherited from that process.

The common use case would be the following:
* In ``define``, use ``inherit_inputs`` for all the processes which are wrapped
* When calling these processes, use ``inherited_inputs`` to pass the inputs to the sub-process.

In addition to reducing code duplication, this also means that the "wrapping" workflow doesn't need to change if one of the sub-workflows changes. 

Note that this implementation could also be moved up (to ``plum.Process`` / ``plum.ProcessSpec``) or down (to ``WorkChain`` / ``WorkChainSpec``). Maybe @muhrin knows best where this belongs.

### CODE REVIEW

**Comment by sphuber** [comment]
Looks good Dominik. I was just thinking that this functionality is generic enough that we might actually prefer to put this down in plum. I am currently working on backporting a feature from our experimental workchain dev branch, to put it in most likely a v0.9.1. This would be ideal moment to also include this feature. Only downside I can see, is that we would have to use an older 0.7.x support release of plum which will later have to be merged with the dev branch of plum. Thoughts @muhrin

**Comment by greschd** [comment]
I'm fine with putting it into plum instead. Let me know if I should create a merge request there.

**Comment by greschd** [comment]
If you are fine with the API, I will also add a short description to the workchain tutorial.

**Comment by sphuber** [comment]
@greschd I went over the proposed design with @muhrin and we came up with some potential issues. 
@muhrin is currently coding this up in plum, but I will give a short overview of our discussion here for reference and so you can also comment on it if you want.

Since the goal of this PR is to make it easier to compose workflows from smaller workflow components, one could easily imagine that a given workflow needs to "inherit" the inputs from multiple workflows. It is also very likely, that these workflows will share inputs with identical names. In the proposed scheme, these input names will clash and one will override the other. So we would need some kind of namespacing. We were also thinking that `inherit` is not the correct word, but maybe `expose` better captures the intent of the spec input. An example interface may look something like the following:

```
class ParentWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super(ParentWorkChain, cls).define(spec)
        spec.input('parameters', valid_type=ParameterData)
        spec.expose(SubAWorkChain, namespace='a')
        spec.expose(SubAWorkChain, namespace='b')

class SubAWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super(SubAWorkChain, cls).define(spec)
        spec.input('parameters', valid_type=ParameterData)

class SubBWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super(SubBWorkChain, cls).define(spec)
        spec.input('parameters', valid_type=ParameterData)
```

We can make the namespace parameter optional, in which case the `Process` will simply take the name of the class of the sub process. Originally we were thinking of unwrapping all these inputs upon instantiating the parent workchain, like it is done now, prepending the namespace to the name of the exposed inputs, but we think this might complicate things. Rather we were now thinking to simply keep the exposed process classes and their namespaces and construct the inputs dynamically.

I realize now, that this discussion is becoming a bit long and unclear, so maybe it is better to continue this in the plum repo.

**Comment by greschd** [comment]
I like the idea of adding a namespace. For the ``inherited_inputs`` (or, ``exposed_inputs``) functions, we would need the ability to **not** prepend the namespace, since the main use of that is to pass the parameters on to the sub-workflow.

Were you thinking of separating the namespace and input name with underscores (``a_parameters``)? Unfortunately, since it should be a valid variable name we can't use ``a.parameters``.

Whether the inputs are created dynamically or statically shouldn't have an impact on the interface, right?

**Comment by greschd** [comment]
Also, indeed using ``inherit`` seems to create a lot of confusion since it's not class inheritance. :+1: for using ``expose``.

**Comment by sphuber** [comment]
You are right that the implementation of input referencing under the hood shouldn't impact the interface, but we do want the current use of `self.inputs` to still work I presume. I think keeping the inputs "unwrapped" and serving them dynamically is the easiest. Also with regards to your example when a user wants a dictionary of inputs of one of the exposed classes, in which case you do not want the namespace to be there. I imagine within the previous example calling `self.inputs.a` will return a dictionary `{'parameters': ParameterData}` which can then be passed straight to `SubAWorkChain`

**Comment by greschd** [comment]
Yeah, that makes a lot of sense.

**Comment by greschd** [comment]
@sphuber I'm wondering if this approach would allow for creating a 'dynamic' input namespace? What I mean is that you have a namespace ``foo``, and dynamic input parameters that start with ``foo_`` are allowed and will get grouped into that namespace. 

This would be really cool for the "dynamic sub-workflow" problem. While my current approach is to have a common input interface (and exposing from an interface class), I can imagine this breaking down if some possible sub-workflows need additional input parameters.

**Comment by sphuber** [comment]
We are no longer going with prefix namespaces, but rather we will keep a simple dictionary of inputs that allows arbitrary amounts of nesting. We could simply add a method to the input dictionary class that allows to add inputs to it dynamically. I don't see right now how that would cause any issues. @muhrin is currently implementing this in an aiida-core branch. It still needs to go in plum eventually, but for logistical reasons it is easier to implement it in aiida-core now and migrate it later on.

**Comment by greschd** [comment]
Just to make sure I understand this correctly: this means that instead of having inputs ``foo_x``, ``foo_y``, and so on in "namespace" ``foo``, you now have *one* input ``foo`` which is a dictionary, and has keys ``x`` and ``y`` and each have a given input type -- is that right?

**Comment by greschd** [comment]
For the ``expose`` function, this would mean that we want to have the choice to expose either at the top level (``SubWF`` has inputs ``bar`` and ``baz``, then ``MainWF`` will also have  ``bar`` and ``baz``), or expose *to some input variable* ``foo`` (``MainWF`` has dict input ``foo``, which has inputs ``bar`` and ``baz``).

**Comment by sphuber** [comment]
Yeah that is what we are thinking off at the moment. Considering your last point, by default I think `MainWF` would take a single input `foo` which is a dictionary containing `bar` and `baz`. Under the hood the input links would of course be drawn directly from `bar` and `baz`. I think you are getting to the situation where exposing inputs of `SubWF` to `MainWF` would mean that you could directly call something like `run(MainWF, bar=bar, baz=baz)`. Do I understand you right? I think we could add this unwrapping as an option, but that should not be the default right? That would mean if you have a workflows that exposes many input sets, you would have to pass them all in an unwrapped way. Although come to think of it, using dictionary expansion this is easy.

**Comment by greschd** [comment]
Yeah the "unwrapped" case would be exactly that. I think there's a use case for both -- depending mainly on how prominent you want the sub-workflow to be. If it should be an implementation detail that your ``MainWF`` is using ``SubWF`` under the hoods, then unwrapping makes sense.

I'm not sure what the default should be. Of course it's easier to make "unwrapped" the default, since you don't need to give the name (``foo``) of the wrapping input variable. We could also differentiate it more clearly by creating two functions ``expose`` (unwrapped) and ``expose_to`` (wrapped).

For passing to the ``SubWF``, in the unwrapped case it would simply be ``run(SubWF, **self.get_exposed_inputs(SubWF))``. In the wrapped case there's not so much use for the ``get_exposed_inputs`` function, since you can just call ``run(SubWF, **self.inputs.foo)``.

**Comment by greschd** [comment]
Another possible use case for "unwrapping" the exposed inputs is if you actually want to **force** two sub-workflows to share an input of the same name.

In ``MainWF``: 
```
spec.expose(SubWF_A)
spec.expose(SubWF_B)
...
run(SubWF_A, **self.get_exposed_inputs(SubWF_A))
run(SubWF_B, **self.get_exposed_inputs(SubWF_B))
```
In ``SubWF_A``
```
spec.input('structure', valid_type=DataFactory('structure'))
spec.input('bar', ...)
```
In ``SubWF_B``

```
spec.input('structure', valid_type=DataFactory('structure'))
spec.input('baz', ...)
```
This would mean they share ``structure``, but not ``bar`` / ``baz``. But I'm also completely fine with having only the "wrapped" version for now, and covering the 90% use cases.

**Comment by sphuber** [comment]
Closing this PR for now. More recent implementation is kept here https://github.com/sphuber/aiida_core/tree/fix_660_expose_workchain_inputs  But depending on timing with the upcoming version of plum, we might include these changes in plum itself, which would be a lot better

**Pull request closed without merging**
