### PR TITLE
Fix orbitaldata

### PR DESCRIPTION
**Pull request by DanielMarchand**

### CODE REVIEW

**Comment by DanielMarchand** [comment]
@giovannipizzi  can you take a look at this? The failures don't seem related to the actual code. E.g

TEST_AIIDA_BACKEND=django TEST_TYPE="docs"
The command "eval git fetch origin +refs/pull/2832/merge: " failed. Retrying, 2 of 3.

**Comment by sphuber** [comment]
@DanielMarchand I don't see the error messages you are mentioning. The tests are running its just that two unit tests are failing.

**Comment by DanielMarchand** [comment]
> @DanielMarchand I don't see the error messages you are mentioning. The tests are running its just that two unit tests are failing.

Thanks, sorry, I was accidentally looking at an old pull request.

**Comment by DanielMarchand** [comment]
@giovannipizzi do you think you could review this & merge if it seems OK?

**Comment by borellim** [comment]
This PR addresses issue #2783.

I had to add another small change to fix class `ProjectionData`. I'm going to add a commit to Daniel's branch for this, and rebase the whole thing onto develop.

**Comment by DanielMarchand** [comment]
@borellim is this still in progress? Looks like this was never merged in. I see some of the tests fail, I can't remember anymore but I was pretty sure the pure orbitaldata changes were passing.

**Comment by borellim** [comment]
I don't know why the tests are failing, nor why this wasn't merged. From my part it was complete. @sphuber?

**Pull request merged**
