### PR TITLE
Removed runtime warnings occurred during restapi unittests

### PR DESCRIPTION
**Pull request by waychal**
Corrected base module path in node translator

### CODE REVIEW

**Comment by sphuber** [comment]
The warnings still show up in the logs of Travis

**Comment by szoupanos** [comment]
@sphuber 
If they still show up, why this was closed?

**Comment by sphuber** [comment]
I temporarily closed the PR so it wouldn't be accidentally merged. Afterwards Snehal added another commit that did fix the issue and this was merged into `release_v0.10.0`. If you check the Travis log of the latest run on that branch you see it is fixed. I am not sure what happened to the notification of the additional commit, which should have shown up here.

**Comment by sphuber** [comment]
Ah I see now, because I closed this PR, Snehal opened a new one that fixed the issue: PR #816

**Comment by szoupanos** [comment]
Great! Thanks a lot both of you!

**Pull request closed without merging**
