### PR TITLE
Implement a generic IdentifierParamType for verdi commands

### LINKED ISSUE #1577: verdi click: implement the generic Identifier ParamType
A very common pattern for any `verdi` command will be an option or an argument that takes on or multiple values that is supposed to identify a specific orm entity. In AiiDA there are three types of identifier:

* ID
* UUID
* STRING

Most entities have both an ID as well as a UUID that identifies them. Some have an additional string based identifier, such as a label or a name.

The logic that parse and retrieve the entity based on a value that could mean any of these three types needs to be defined so it can be easily reused

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #1577 

A very common pattern for any verdi command will be an option or an argument
that takes on or multiple values that is supposed to identify a specific orm
entity. In AiiDA there are three types of identifier:

 * ID
 * UUID
 * LABEL

Most entities have both an ID as well as a UUID that identifies them. Some
have an additional string based identifier, such as a label or a name.

Here we define the class IdentifierParamType, which can be used to create
reusable arguments and options that will load ORM instances based on the
passed values, by deducing whether they are meant to repesent an ID, UUID
or LABEL. Note that since the type is lost and all values will be strings,
one has to guess the type. The value will be attempted to be interpreted
as an ID, UUID and then LABEL, in that order.

This approach can lead to ambiguities in some situations, where if an
intended (partial) UUID can be interpreted as a valid ID. Or when a valid
LABEL also happens to be a valid ID. However, as long as the users do
not use labels that are valid integers and use the full UUID in the worst
case, chances for these clashes should be highly unlikely.

### CODE REVIEW

**Comment by sphuber** [comment]
My reasoning for considering the ID before the UUID is because, if a partial UUID is mistaken for an ID, one can always provide a bigger part of the UUID to solve the ambiguity. The dashes of the entire UUID will directly disqualify it as an integer, but even without dashes, the chances of having a full UUID that consists solely of numbers is highly unlikely.

Conversely, if we were to consider the UUID before an ID, then if one passes a value that is supposed to be interpreted as an ID, but it so happens that a UUID exists that starts with those numbers, which is highly likely, there is no way to solve the ambiguity.

Both orders have potential for ambiguity, but I think the former is way more unlikely to occur compared to the latter.

Concerning the string label/name, it is exactly as you say for example for the label of the codes (either with machine name or without), the name of Groups or the name of Computers, etc. The implementation fine control over how the STRING is defined for a given ORM class and how it should be queried. It is true, that since it is considered last, if a STRING label is used that is valid hexadecimal, there will be a problem. We could try to come up with some conditional option that can be added for commands where this ambiguity is likely, but I would be wary of it. Rather, I would tell users soon about the way identifiers work in AiiDA and discourage hex-like identifiers. As much as I would like to name my computer `deadbeef` I think that the consistency in behavior is more valuable than creating all sorts of weird exceptions and parsing rules.

**Comment by giovannipizzi** [comment]
I fully agree on your comment on ID before UUID, still before the trick of the dash I wasn't fully convinced. Now I am.
Instead, for the STRING, I'm not convinced yet. It's too much large of a namespace to block all names with digits and letters abcdef (and it's not nice to tell users to change the name of the computer - e.g. if a supercomputer center calls the computer `deadbeef` it's weird to tell the user to call it something else).

For parsing and distinguishing, I would just see if this can be put at the cmdline level, in a single place.

Otherwise, following the reasoning you mention for ID vs UUID, I think then that it's much more natural to have the order STRING - ID - UUID as, if the STRING overlaps, one can always change it (and the issue is mainly with the ID, so if one gives a purely numeric STRING; for the UUID, the problem can be solved as you describe before). In this case then, it's fair to tell users soon, as you suggest, that this is the rule so, if they want to give a numeric string to a code or computer, it's their problem.

**Comment by sphuber** [comment]
I have implemented the infrastructure necessary to narrow the query set of orm classes per instance of `IdentifierParamType`. This is done based on the entry point strings, allowing the loading of the database environment only when the type is called to convert a value. The loaded entry points are cached so that they only have to be loaded once per instantiated identifier parameter type. Note that the interface supports passing a tuple of allowed orm classes, however, the query builder currently does not. For the moment, I literally just take the first element, so when the query builder is updated, it is as easy as removing the `[0]` from the `.append` calls in the `aiida.orm.utils.loaders` query builder functions

**Comment by sphuber** [comment]
This was not supposed to be merged yet, as it depends on the QueryBuilder fix that was not yet merged. I also hadn't added all the tests yet. I will fix this directly in the `verdi` branch now, into which this was merged. I will do this directly, so just so you know that you will have to reset your HEAD if you had it checked out locally

**Pull request merged**
