### PR TITLE
Update sphinx_rtd_theme to 0.2.5b2 to fix line numbers of code snippets in docs

### LINKED ISSUE #1041: documentation: line numbers in code-blocks don't match actual lines
Example: Search for "Here is the code:" on http://aiida-core.readthedocs.io/en/latest/work/index.html

This is a known bug in sphinx_rtd_theme, which has been fixed in v0.2.5
https://github.com/rtfd/sphinx_rtd_theme/issues/415

To do: Update `setup_requirements.py` accordingly and check that the problem is gone.

### PR DESCRIPTION
**Pull request by yakutovicha**
Fixes #1041 

To correct the appearance of line numbers in the documentation I
updated the sphinx_rtd_theme to the latest version (0.2.5b2). The bug
was fixed in the version 0.2.5b1

### CODE REVIEW

**Comment by sphuber** [comment]
Just as a comment regarding formatting PR's. It is very useful for when releases have to be made, to have an as descriptive title as possible for the PR. The person making the PR can then immediately see what the fix was. The actual issue can be described in the PR message body. To automatically have the corresponding issue closed use as a first line "This fixes #1041". Although unfortunately this only works if we merge into `develop`.

The same goes for commit messages by the way. Please use the first line as a really descriptive title. Just saying 'fix issue 1041' will not really be useful when reading the commit logs in the future.

**Comment by vbotka** [comment]
#1041: "line numbers in code-blocks don't match actual lines" is closed with the comment "Fixed in #1044". Let's proceed here.

Today I completed the Build #6752013 and still see "line numbers in code-blocks don't match actual lines"
http://redis-c-examples.readthedocs.io/en/latest/examples.html#create-frequency-graph-from-a-log

What am I missing?

**Comment by ltalirz** [comment]
@vbotka Good point... it is fixed when building the documentation locally, but we didn't update the requirements read by ReadTheDocs. Will do this in a minute.

**Comment by vbotka** [comment]
Today I competed the Build #6780801 and still the "line numbers in code-blocks don't match actual lines".
[redis-c-examples.readthedocs.io](http://redis-c-xamples.readthedocs.io/en/latest/examples.html#create-frequency-graph-from-a-log)
What am I missing?

**Comment by giovannipizzi** [comment]
Thanks for the report. We are aware of it, and the original solution was not enough. We (actually, @ltalirz) fixed the documentation problem (documentation wasn't compiling anymore) but RTD keeps using the old version of the theme. We might know how to fix it (we have to add in the conf.py an explicit reference to the theme, otherwise RTD uses its default one), but we couldn't fix it yet. We hope to be able to check if this solution works within a few days.

**Pull request merged**
