### PR TITLE
Add test for availability of sudo in quicksetup

### LINKED ISSUE #2004: verdi quicksetup assumes presence of sudo
Reported by @yakutovicha on AiiDA lab (aiida v0.12.2)

```
Profile name [quicksetup]: test
Email Address (identifies your data when sharing): test@gmail.com
First Name: test
Last Name: test
Institution: test
Traceback (most recent call last):
  File "/usr/local/bin/verdi", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 1050, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 1035, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 622, in run
    quicksetup.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, args, *kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 655, in quicksetup
    success = postgres.determine_setup()
  File "/usr/local/lib/python2.7/dist-packages/aiida/control/postgres.py", line 113, in determine_setup
    non_interactive=bool(not self.interactive), **dbinfo):
  File "/usr/local/lib/python2.7/dist-packages/aiida/control/postgres.py", line 281, in _try_subcmd
    _pg_execute_sh(r'\q', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aiida/control/postgres.py", line 345, in _pg_execute_sh
    result = subprocess.check_output(sudo_su_psql, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subprocess32.py", line 629, in check_output
    process = Popen(stdout=PIPE, popenargs, *kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subprocess32.py", line 825, in _init_
    restore_signals, start_new_session)
  File "/usr/local/lib/python2.7/dist-packages/subprocess32.py", line 1574, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'sudo'
```

This seems to apply both in master:
https://github.com/aiidateam/aiida_core/blob/651a09a60be4dfe34ec97d6f45fbe6e377af2c86/aiida/control/postgres.py#L345

and in develop:
https://github.com/aiidateam/aiida_core/blob/9ec944564bc7e4c2af58b17f0711d1c25be8b4b6/aiida/control/postgres.py#L334

To Do:
 - [ ] figure out whether one just needs to wrap it in try/except or whether there is a (failing) check on the presence of sudo before this
 - [ ] fix bug in master and develop

### PR DESCRIPTION
**Pull request by ConradJohnston**
Partially addresses #1382 

Quicksetup needs to access the Postgres database, but does not know anything about the system setup. It initially tries to see if it is the postgres superuser, but if it is not, it tries to become the Postgres superuser via sudo. This is the "backstop" position and relies on the user having a modern Linux-like system.
If, however, the sudo command is not available to this user at all (for example, perhaps the user is on an HPC cluser with command hidden), a system error will be raised and quicksetup will fail ungracefully. 

This commit adds a test to see if sudo can be found before attempting to use it, prints a warning, and then falls back to the 'Postgres not detected' behaviour.

### CODE REVIEW

**Comment by sphuber** [comment]
@yakutovicha will this solve the original issue you had? If I understand correctly it was trying to use `sudo` to connect to `postgres`, but the machine on which you were running this didn't have `sudo`, is that right? If that was the problem, although better, this will not solve the actual problem? Is there a fallback option for the quicksetup in this situation?

**Comment by ConradJohnston** [comment]
Hi @sphuber , this is an interesting part of the issue. I spent some time looking at how we can connect to the database, but the long and short of it is that without being the postgres user, or another user with superuser permissions for postgres, one needs sudo to create a new database.  In normal setup, the user must have created the database already, but in quicksetup it is done automatically. However, in both situations the same constraints are there.

**Comment by ConradJohnston** [comment]
Actually I've found one can start a new instance of Postgres in their user space and connect with their user as a superuser, provided that it's configured to use a port that isn't in use by the system postgres.  Should we support this as an option after failing to find sudo?

**Comment by sphuber** [comment]
After discussion with @ltalirz we are going to merge this PR in, but we are keeping issue #1382 open. It looks like there is a bug in the postgres control module that was not properly detecting when a user has postgres rights and so was always defaulting to trying `sudo` which is what the source of the issue. Apparently, this particular origin has been fixed in `develop`. Issue #1382 should remain open to backport this fix onto `0.12.3`.

**Pull request merged**
