### PR TITLE
Ensure that `export_tree` respects `create_reversed` for Data nodes

### LINKED ISSUE #2068: `create_reversed` is not respected for Data -> Calculation when set to `False`
In the graph traversal section in `aiida.orm.importexport.export_tree`, the flag `create_reversed` does get considered when adding potential nodes going from `Calculation` to `Data`, but when considering `Data` nodes the flag is omitted. As a result, when one just wants to export a `Group` with some `Data` nodes, without any of the creating calculations, one cannot.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #2068 

The `create_reversed` flag was only being applied when traversing the
graph from a `Calculation` to `Data` node, but not reversed. This made
it impossible to export _only_ data nodes without its creators even
if `create_reversed` was set to `False`.

### CODE REVIEW

**Comment by szoupanos** [comment]
My understanding is that we always follow the CREATE nodes in Reverse (look at the rules at the following set of rules: https://github.com/aiidateam/aiida_core/issues/1102#issuecomment-383090834) since we would like to keep the provenance (who cerated them).

Seb has a valid argument that he would like to give some data nodes to a colleague and if he includes the cals, the number of export nodes increases by an order of magnitude (if I understood well) and he would like to avoid it.

It is a very easy fix, just let's take a common decision on this (@giovannipizzi @ltalirz )

**Comment by sphuber** [comment]
Note that the default behavior won't be changed by this fix, because the default for `create_reversed` argument in `export_tree` is set to `True`. So by default, the original behavior will be kept

**Comment by ltalirz** [comment]
To me, the basic assumption for all rows in the the table in https://github.com/aiidateam/aiida_core/issues/1102#issuecomment-383090834 should always be "User can modify default behavior".

We can then decide which of these modifications we actually implement (some of them may be too crazy), but I would say we should not limit the user in what can be exported from her or his graph.

**Comment by szoupanos** [comment]
I am approving this (I have nothing against giving such freedom to the user). I would like to think (and maybe all of us brainstorm) on which cases we would like to prevent an export file to be imported. 

This is related to @ltalirz comment at
https://github.com/aiidateam/aiida_core/issues/1842#issuecomment-430548256

Obviously if there are such cases, such export files should not exist and consequently the export rules should not allow such files to be created.

**Pull request merged**
