### PR TITLE
Ignore when trying to make a link of the same type as an existing one

### PR DESCRIPTION
**Pull request by greschd**
Solves #641. I'm not really sure if this might not have unintended consequences. The test which explicitly checks that the ``UniquenessError`` is raised fails, but it might be ok to remove that.

### CODE REVIEW

**Comment by greschd** [comment]
Closing in favor of #645.

**Comment by greschd** [comment]
So in the interest of keeping everything as close as possible to the previous version I'm guessing we don't want to change anything in ``_replace_link_from``, correct?

**Comment by DropD** [comment]
The issue this relates to (#641) seems to be closed. Is there any reason to keep this PR open?

**Comment by greschd** [comment]
Yes, if I'm not mistaken the PR that fixed #641 was reverted because it introduced a bug. @sphuber should know if that was fixed in the meantime. This is an alternative way to solve the issue.

**Comment by sphuber** [comment]
Yes, the PR that I merged to fix this turned out to break the legacy workflows in a subtle but nasty manner, so I reverted those commits. I have the feeling that after that I also merged this fix, in a different PR, i.e. remove the uniqueness constraint in the `add_link_from` and `replace_link_from` methods, but can't shake the feeling that that also turned out to break stuff and hence reverted it. I should check in the commits.

**Comment by greschd** [comment]
It seems these changed haven't been merged / reverted in develop: https://github.com/aiidateam/aiida_core/commits/develop/aiida/orm/implementation/general/node.py

For what it's worth, I'm running this in my development branch, and haven't found an issue yet.

**Comment by sphuber** [comment]
But the `UniquenessError` that was originally giving you issues with your `WorkChain` is currently still in develop. How is it possible that it works now? Can you with the current state of `develop` run a `WorkChain` while passing the same node as input multiple times albeit it with different labels?

**Comment by greschd** [comment]
Not with the current state of ``develop``, what I meant is that in the branch where I collect newer features this runs without problems (as far as I can tell).

**Comment by sphuber** [comment]
Yes but as I recall, removing the `UniquenessError` will break the legacy workflows. You don't run those do you? I would have to apply this PR locally and run some legacy workflows to make sure. Just looking at the code, I can't quite work out anymore why it would fail, but I am not certain that it in fact doesn't

**Comment by greschd** [comment]
Indeed, I wasn't running any legacy workflows.

**Pull request merged**
