### PR TITLE
Fix Setup / Quicksetup more permanently

### LINKED ISSUE #291: Add test that quicksetup works in a clean (virtual) environment
Originally reported by: **Tiziano Müller (Bitbucket: [dev-zero](https://bitbucket.org/dev-zero), GitHub: [dev-zero](https://github.com/dev-zero))**

----------------------------------------

In ` setup.py` there is currently a `from aiida import get_version` to keep the version in sync.
This means that 'import aiida' can only import packages which are part of a Python installation.

The easiest test for that is to do a `python -c "import aiida"` inside a virtual environment (created using `virtualenv venv` and activated using `. ./venv/bin/activate`).

Furthermore we need tests to ensure that `verdi install` always works without an already defined database and without existing configuration.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/291

### LINKED ISSUE #747: Problem during verdi setup (maybe connected to new control module?)
E. Bosoni reports the following error when doing verdi setup SiestaAiidaTest
```
verdi setup SiestaAiidaTest
Setting up profile SiestaAiidaTest.
AiiDA backend (available: django, sqlalchemy - sqlalchemy is in beta mode): django
Default user email: [xxx]@[xxx.yy]
Database engine (available: postgresql_psycopg2, mysql - mysql is deprecated): postgresql_psycopg2
PostgreSQL host: localhost
PostgreSQL port: 5432
AiiDA Database name: siestatestdb
AiiDA Database user: siestatest
AiiDA Database password: XXXXXX
AiiDA repository directory: /home/yyy/TestAiidaSiestapy/.aiida/repository-SiestaAiidaTest/
The repository /home/yyy/TestAiidaSiestapy/.aiida/repository-SiestaAiidaTest/ will be created.
Executing now a migrate command...
...for Django backend
Operations to perform:
  Apply all migrations: sessions, db, sites, kombu_transport_django, contenttypes, auth
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying db.0001_initial... OK
  Applying db.0002_db_state_change... OK
  Applying db.0003_add_link_type... OK
  Applying db.0004_add_daemon_and_uuid_indices... OK
  Applying db.0005_add_cmtime_indices... OK
  Applying kombu_transport_django.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
== Postgres found, installing transitive closure engine ==
Database was created successfully
Loading new environment...
Installing default AiiDA user...
Starting user configuration for xxx@xxxx.yy...
First Name: Xxx
Last Name: Yyy
Institution: Zzz
Traceback (most recent call last):
  File "/home/xxx/TestAiidaSiestapy/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/xx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 353, in run
    _setup_cmd.invoke(ctx)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 407, in _setup_cmd
    setup(**kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 590, in setup
    user.configure.main(args=[email])
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/commands/user.py", line 152, in configure
    do_configure(email, first_name, last_name, institution, no_password)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/commands/user.py", line 62, in do_configure
    user, created = get_or_new_user(email)
TypeError: get_or_new_user() takes exactly 0 arguments (1 given)
```
Is this expected? Probably it happened after the new `aiida.control` module has been created?

BTW, the name of the function is strange, it should probably be `get_or_create_user`? or `new` is used instead of `create` (but it's not a verb...)?

### LINKED ISSUE #752: Tests missing: setup / quicksetup with user configuration
Currently both `verdi setup` as well as `verdi quicksetup` are broken if not used with the default email. In this case both of them try to configure a new user. This has caused no test faillure.

### LINKED ISSUE #764: verdi setup error during user configuration
The error message is the following:

File "/hith/codes/aiida_core/aiida/cmdline/commands/user.py", line 77, in do_configure
for field in User.REQUIRED_FIELDS:
AttributeError: type object 'User' has no attribute 'REQUIRED_FIELDS'

Should be fixed by putting the import (in aiida/cmdline/commands/user.py, "do_configure" method).

from aiida.orm.implementation import User

### LINKED ISSUE #796: Error prompt_db_info() takes no arguments (2 given) when running verdi quicksetup
Running "verdi quicksetup" in release_v0.10.0 raises the following error:
```
(aiida) elsa@inspiron:~/aiida_core$ verdi quicksetup
Profile name [quicksetup]: 
Email Address (identifies your data when sharing): user@epfl.ch
First Name: Elsa
Last Name: Passaro
Institution: EPFL
Detected no known postgres setup, some information is needed to create the aiida database and grant aiida access to it.
If you feel unsure about the following parameters, first check if postgresql is installed.
If postgresql is not installed please exit and install it, then run verdi quicksetup again.
If postgresql is installed, please ask your system manager to provide you with the following parameters:
Traceback (most recent call last):
  File "/home/elsa/.virtualenvs/aiida/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/elsa/aiida_core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/elsa/aiida_core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/elsa/aiida_core/aiida/cmdline/verdilib.py", line 614, in run
    self._quicksetup_cmd.invoke(ctx)
  File "/home/elsa/.virtualenvs/aiida/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elsa/.virtualenvs/aiida/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/elsa/.virtualenvs/aiida/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/elsa/aiida_core/aiida/cmdline/verdilib.py", line 646, in _quicksetup_cmd
    postgres.determine_setup()
  File "/home/elsa/aiida_core/aiida/control/postgres.py", line 103, in determine_setup
    self._no_setup_detected()
  File "/home/elsa/aiida_core/aiida/control/postgres.py", line 181, in _no_setup_detected
    self.dbinfo)
TypeError: prompt_db_info() takes no arguments (2 given)
```

### PR DESCRIPTION
**Pull request by DropD**
Introduce tests for setup / quicksetup (for travis only, since having them clean up touches live config files). Fix bugs until the tests pass.
* fix #764
* fix #752
* fix #291 
* fix #796
* fixes `quicksetup` (no issue for that yet, only bug report via email)

### CODE REVIEW

**Comment by DropD** [comment]
@giovanni This fixes `quicksetup`

**Comment by ltalirz** [comment]
Thanks a lot for doing a _proper_ fix of this!

I just checked out your pull request and tested quicksetup. The error I was getting before is now gone, but there still seems to be the problem with the `REQUIRED_FIELDS` mentioned by nmounet in #747 

```
$ verdi quicksetup
Profile name [quicksetup]: test-rico
Email Address (identifies your data when sharing): leopold.talirz@epfl.ch
First Name: Leopold
Last Name: Talirz
Institution: EPFL
using found password for aiida_qs_leopold
Executing now a migrate command...
...for Django backend
Operations to perform:
  Apply all migrations: sessions, db, sites, kombu_transport_django, contenttypes, auth
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying db.0001_initial... OK
  Applying db.0002_db_state_change... OK
  Applying db.0003_add_link_type... OK
  Applying db.0004_add_daemon_and_uuid_indices... OK
  Applying db.0005_add_cmtime_indices... OK
  Applying kombu_transport_django.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
== Postgres found, installing transitive closure engine ==
Database was created successfully
Loading new environment...
Installing default AiiDA user...
Starting user configuration for leopold.talirz@epfl.ch...

An AiiDA user for email 'leopold.talirz@epfl.ch' is already present in the DB:
Do you want to reconfigure it? [y/N]: y
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1041, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1026, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 616, in run
    quicksetup.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 731, in quicksetup
    setup(profile_name, only_config=False, non_interactive=True, **setup_args)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 597, in setup
    True)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/commands/user.py", line 77, in do_configure
    for field in User.REQUIRED_FIELDS:
AttributeError: type object 'User' has no attribute 'REQUIRED_FIELDS'
```

**Comment by ltalirz** [comment]
You let me know, when you want me to have another look, right?

**Comment by nmounet** [comment]
Can we also fix #764 (which anyway is probably blocking the proper completion of the tests), with this PR?

**Comment by DropD** [comment]
there are now tests and fixes for all the bugs

**Pull request merged**
