### PR TITLE
remove unused dependencies

### LINKED ISSUE #2800: dependency cleanup
Following the discovery of the superfluous `chainmap` dependency, I've made a list of all AiiDA dependencies that are used in less than 2 files in the current `develop` codebase.

I understand that some versions may be pinned for a reason - if this is the case, please let me know. I've used `pipdeptree` to figure out whether packages are *only* dependencies of aiida-core ("top-level dependency") or *also* dependencies of other dependencies (which may result in a different version being installed when removing the version pinning).

Vote to remove:
 - [x] python-mimeparse (mimeparse): never used, top-level dependency
 - [x] anyjson: never used, top-level dependency
 - [ ] ~~psutil: never used directly, also dependency of `circus` (any version). perhaps this pinning should remain?~~ starts to be used in #2795 
 - [x] meld3 (pymeld): never used, top-level dependency
 - [ ] ujson (ultrajson): used in [`aiida/backends/sqlalchemy/utils.py`](https://github.com/aiidateam/aiida_core/blob/8b6169c9ff60a9ed120969b53a687f5925a1e51d/aiida/backends/sqlalchemy/utils.py#L13-L15) but with a try/except, top-level dependency
- [x] click-plugins (click_plugins): apparently never used (?). It seems to me this is actually not needed (would need to check), top-level dependency
- [x] ecdsa: never used, top-level dependency
- [ ] ~~pika: used in `aiida/engine/processes/process.py`, however: (1) it's just using a pika exception; perhaps this can be replaced. (2) pika is a dependency of `kiwipy[rmq]`. Shouldn't we let kiwipy decide the version to install?~~ We keep it for the moment (to be removed once pika is no longer used directly)

Fine to stay - suggestions welcome if functionality can be replaced by existing dependencies:
 - [ ] tzlocal: used in `aiida/common/timezone.py`
 - [ ] passlib: used in `aiida/common/hashing.py`
 - [ ] click-completion: used in `aiida/cmdline/commands/__init__.py`, `aiida/cmdline/commands/cmd_completioncommand.py`
 - [ ] click-spinner (click_spinner): used in `aiida/cmdline/commands/cmd_daemon.py`, `aiida/cmdline/utils/decorators.py`
- [ ] ete3: used in `aiida/cmdline/commands/cmd_node.py`, `aiida/cmdline/utils/ascii_vis.py`.  
- [ ] pyblake2: used in `aiida/common/hashing.py`
- [ ] simplejson: used in `aiida/common/json.py`

@giovannipizzi @sphuber please let me know your opinion and I will prepare the PR

### PR DESCRIPTION
**Pull request by ltalirz**
fix #2800

### CODE REVIEW

**Comment by ltalirz** [comment]
How is it possible that tests are failing for python 3.6 when the dependency I removed was only installed for python <3.5?

**Comment by ltalirz** [comment]
Ok... randomness..

**Comment by sphuber** [comment]
Shall we wait with merging this and simply include it in your PR that you are preparing now to remove all other unnecessary dependencies?

**Comment by ltalirz** [comment]
Sure, we can do that.
Please merge the one for release_v0.12.4 already, however (not sure I'll remove the other dependencies there as well, but chainmap breaks the conda forge build)

**Comment by sphuber** [comment]
> Sure, we can do that.
> Please merge the one for release_v0.12.4 already, however (not sure I'll remove the other dependencies there as well, but chainmap breaks the conda forge build)

done

**Comment by ltalirz** [comment]
@sphuber ready for review

**Pull request merged**
