### PR TITLE
WIP: Tc wo dbpath

### PR DESCRIPTION
**Pull request by lekah**
This pull request will remove the DbPath table

### CODE REVIEW

**Comment by lekah** [comment]
@szoupanos One test for export/import is failing, but only for the SQLAlchemy backend. My guess is that this is a problem relating to the export script. Could you check?

**Comment by szoupanos** [comment]
Here is a "dirty" that demonstrates the problem

```
    def test_6b(self):
        """
        This test checks that nodes belonging to user A (which is not the
        default user) can be correctly exported, imported, enriched with nodes
        from the default user, re-exported & re-imported and that in the end
        all the nodes that have been finally imported belonging to the right
        users.
        """
        import os
        import shutil
        import tempfile

        from aiida.orm import load_node
        from aiida.orm.calculation.job import JobCalculation
        from aiida.orm.data.structure import StructureData
        from aiida.orm.importexport import export
        from aiida.common.datastructures import calc_states
        from aiida.common.links import LinkType
        from aiida.common.utils import get_configured_user_email
        from aiida.orm.user import User
        from aiida.orm.querybuilder import QueryBuilder
        from aiida.orm.node import Node

        # Creating a folder for the import/export files
        temp_folder = tempfile.mkdtemp()
        try:
            # Create another user
            new_email = "newuser@new.n"
            user = User(email=new_email)
            user.force_save()

            # Create a structure data node that has a calculation as output
            sd1 = StructureData()
            sd1.dbnode.user = user._dbuser
            sd1.label = 'sd1'
            sd1.store()

            jc1 = JobCalculation()
            jc1.set_computer(self.computer)
            jc1.set_resources({"num_machines": 1, "num_mpiprocs_per_machine": 1})
            jc1.dbnode.user = user._dbuser
            jc1.label = 'jc1'
            jc1.store()
            jc1.add_link_from(sd1)
            jc1._set_state(calc_states.PARSING)

            # Create some nodes from a different user
            sd2 = StructureData()
            sd2.dbnode.user = user._dbuser
            sd2.label = 'sd2'
            sd2.store()
            sd2.add_link_from(jc1, label='l1', link_type=LinkType.CREATE)

            # Set the jc1 to FINISHED
            jc1._set_state(calc_states.FINISHED)

            print "sd1.uuid ===> ",sd1.uuid
            print "jc1.uuid ===> ", jc1.uuid
            print "sd2.uuid ===> ", sd2.uuid

            print "OOOOOO1 ====>", QueryBuilder().append(Node, tag='high_node',
                                  filters={'uuid': {'in': [sd1.uuid]}}).append(Node,
                                                                         descendant_of='high_node',
                                                                         project=[
                                                                             '*']).all()

            # At this point we export the generated data
            filename1 = os.path.join(temp_folder, "export1.tar.gz")
            export([sd2.dbnode], outfile=filename1, silent=True)
            uuids1 = [sd1.uuid, jc1.uuid, sd2.uuid]
            self.clean_db()
            self.insert_data()
            import_data(filename1, silent=True)

            print "sd1.id ===> ", load_node(sd1.uuid).id
            print "jc1.id ===> ", load_node(jc1.uuid).id
            print "sd2.id ===> ", load_node(sd2.uuid).id

            from aiida.backends.sqlalchemy.models.node import DbLink
            from aiida.backends.sqlalchemy import get_scoped_session
            session = get_scoped_session()
            print "LLLLLL => ", session.query(DbLink.input_id, DbLink.output_id,
                                               DbLink.label).all()

            print "AAAAAAA ====>", QueryBuilder().append(Node, project=['*']).all()

            sd2_imp = load_node(sd2.uuid)

            jc2 = JobCalculation()
            jc2.set_computer(self.computer)
            jc2.set_resources({"num_machines": 1, "num_mpiprocs_per_machine": 1})
            jc2.label = 'jc2'
            jc2.store()
            jc2.add_link_from(sd2_imp, label='l2')
            jc2._set_state(calc_states.PARSING)

            sd3 = StructureData()
            sd3.label = 'sd3'
            sd3.store()
            sd3.add_link_from(jc2, label='l3', link_type=LinkType.CREATE)

            # Set the jc2 to FINISHED
            jc2._set_state(calc_states.FINISHED)

            # Store the UUIDs of the nodes that should be checked
            # if they can be imported correctly.
            uuids2 = [jc2.uuid, sd3.uuid]

            print "WWWWWW ====>", QueryBuilder().append(Node, tag='low_node',
                                  filters={'id': {'in': [sd3.id]}}).append(Node,
                                                                         ancestor_of='low_node',
                                                                         project=[
                                                                             '*']).all()


            print "OOOOOO2 ====>", QueryBuilder().append(Node, tag='high_node',
                                  filters={'uuid': {'in': [sd1.uuid]}}).append(Node,
                                                                         descendant_of='high_node',
                                                                         project=[
                                                                             '*']).all()

        finally:
            # Deleting the created temporary folder
            shutil.rmtree(temp_folder, ignore_errors=True)
```

And the output is

```
sd1.uuid ===>  063bccf8-e487-4c9d-9a54-ed9c26be37ca
jc1.uuid ===>  8cf3f6b4-7e00-4ddf-8f97-3a73ee02f93e
sd2.uuid ===>  4e5a7597-c03d-4f48-b8e4-ceab809e2b08
OOOOOO1 ====> [[<JobCalculation: uuid: 8cf3f6b4-7e00-4ddf-8f97-3a73ee02f93e (pk: 7721)>], [<StructureData: uuid: 4e5a7597-c03d-4f48-b8e4-ceab809e2b08 (pk: 7722)>]]
sd1.id ===>  7723
jc1.id ===>  7724
sd2.id ===>  7725
LLLLLL =>  [(7723, 7724, u'link_1'), (7724, 7725, u'l1')]
AAAAAAA ====> [[<StructureData: uuid: 063bccf8-e487-4c9d-9a54-ed9c26be37ca (pk: 7723)>], [<JobCalculation: uuid: 8cf3f6b4-7e00-4ddf-8f97-3a73ee02f93e (pk: 7724)>], [<StructureData: uuid: 4e5a7597-c03d-4f48-b8e4-ceab809e2b08 (pk: 7725)>]]
WWWWWW ====> [[<JobCalculation: uuid: 9b78aa9e-a2f3-496c-9568-6b39c53f8919 (pk: 7726)>], [<StructureData: uuid: 4e5a7597-c03d-4f48-b8e4-ceab809e2b08 (pk: 7725)>]]
OOOOOO2 ====> []
```

The "problem" is that after the import:
- all the needed nodes are imported (AAAAAAA print statement)
- there are links connecting the right nodes (LLLLLL print statement)
- Not all ancestors of sd3 are discovered (WWWWWW print statement)
- None of the descendants of sd1 is found (OOOOOO2 print statement)

The above is very related to the reason why test6 is failing. 
My understanding is that test6 was working fine before the change in transitive closure.
Moreover the above test works as expected if we avoid to export and import sd1, jc1, sd2 in the middle of the test.

So something goes wrong with the imported links and for some reason they are not discoverable by QueryBuilder.

I will try to look closer.

**Comment by szoupanos** [comment]
Moreover, the migration mechanism for SQLA is ready to be used and it is documented #614.
So a migration script for SQLA should be written too

**Comment by szoupanos** [comment]
I looked a bit closer at this and it seems that there is no link type stored in the database for the imported nodes. This needs to be corrected (I suppose in another ticket/pull request) and the correct link type should be exported and imported. The exported/imported link types should be in line with the new link types that we recently discussed.

Moreover, the reason of the failure seems to be the type of the imported links in SQLA. It seems that the following descendant query 
```
QueryBuilder().append(Node, tag='high_node',
                                  filters={'uuid': {'in': [sd1.uuid]}}).append(Node,
                                                                         descendant_of='high_node',
                                                                         project=[
                                                                             'id']).all()
``` 

that is translated in SQL as

```
WITH RECURSIVE anon_2(ancestor_id, descendant_id, depth) AS 
(SELECT db_dblink_1.input_id AS ancestor_id, db_dblink_1.output_id AS descendant_id, CAST(0 AS INTEGER) AS depth 
FROM db_dbnode AS db_dbnode_3 JOIN db_dblink AS db_dblink_1 ON db_dblink_1.input_id = db_dbnode_3.id 
WHERE CAST(db_dbnode_3.type AS VARCHAR) LIKE '%' AND db_dbnode_3.uuid IN ('3835fa59-2211-4768-a42c-7166aebec65e') AND db_dblink_1.type != 'returnlink' UNION ALL SELECT anon_2.ancestor_id AS ancestor_id, db_dblink_2.output_id AS descendant_id, anon_2.depth + CAST(1 AS INTEGER) AS current_depth 
FROM anon_2 JOIN db_dblink AS db_dblink_2 ON db_dblink_2.input_id = anon_2.descendant_id 
WHERE db_dblink_2.type != 'returnlink')
 SELECT db_dbnode_1.id 
FROM db_dbnode AS db_dbnode_2 JOIN anon_2 AS anon_1 ON anon_1.ancestor_id = db_dbnode_2.id JOIN db_dbnode AS db_dbnode_1 ON anon_1.descendant_id = db_dbnode_1.id 
WHERE CAST(db_dbnode_2.type AS VARCHAR) LIKE '%' AND db_dbnode_2.uuid IN ('3835fa59-2211-4768-a42c-7166aebec65e') AND CAST(db_dbnode_1.type AS VARCHAR) LIKE '%'
```

returns correct results when the type of imported links is '' (Empty string) and no results when it is NULL.

We should have a coherent way to represent empty types and this, very likely, should be corrected with a database migration for already created empty links.

**Comment by sphuber** [comment]
The branch related to this PR has been merged in the `fix_export_import` branch which will also contains the necessary fixes that keep this PR from merging. I will close this PR and create a new one from the `fix_export_import` branch once all necessary fixes are in place.

**Pull request closed without merging**
