### PR TITLE
Verdi cmdline/commands improvements

### PR DESCRIPTION
**Pull request by dev-zero**
Besides fixing a couple of things like using the `with_dbenv` decorator instead of manually using `load_dbenv` and delaying the db loading into the commands, or fixing the `Pluginable` class' `list_commands`, this also wires up data plugins until `VerdiSubcommand` can be dropped.

### CODE REVIEW

**Comment by dev-zero** [comment]
@DropD tests for 3842cd5 are still running, but the commits before should be fine even without the last one.

**Comment by dev-zero** [comment]
While commit 3842cd5 adds the plugin commands, it adds them twice in `verdi data --help`: calling `get_help()` (in `verdilib.py`) on the context not only causes `list_commands` from `Pluginable` to be called, but also the `get_command()` on each subcommand (for the description), causing the plugins to be loaded and therefore register themselves with click. Now, when `list_commands` is then called a second time by click itself to display the help, the plugin commands are already registered in the `click.Group` (possibly even under a different name).

**Comment by dev-zero** [comment]
@DropD just rebased, hope that was ok

**Comment by DropD** [comment]
@dev-zero can you rebase again?

**Comment by sphuber** [comment]
I will just merge in `verdi` and then squash merge the commits

**Pull request merged**
