### PR TITLE
[WIP] Fix launching builder with free-function submit

### PR DESCRIPTION
**Pull request by greschd**
Added a failing test for ``submit(builder)``. 

@sphuber I don't really know how to fix this, because I don't fully understand the problem when just using ``runners.get_runner().submit(builder)``.  Or in other words, what kind of ``Runner`` could we use to do the right kind of submitting?

### CODE REVIEW

**Comment by greschd** [comment]
As a workaround we could just pull out the logic that handles the ``JobCalculation`` and ``ProcessBuilder`` into a function, and then use the original method of submitting. But yeah, that's kinda ugly.

**Comment by greschd** [comment]
I don't see exactly why there are two ways to instantiate a process, either with the ``ControlPanel.execute_process_start``, or with the ``runners.instantiate_process``.

**Comment by sphuber** [comment]
I could have sworn I fixed that when I cleaned up all those functions, but apparently the fix for `submit` was not committed. Anyway, I add it here now and it should be fixed now

**Comment by greschd** [comment]
Ha, and I could've sworn I tried exactly that code to fix it but it didn't work. Anyway, it works now :+1:

**Pull request merged**
