### PR TITLE
Replacement: Issue 702 streamline plugin dev docs

### LINKED ISSUE #701: Plugin development docs should mention `reentry` install hooks
The plugin's `setup.py` should contain

```python
setup(
    ...
    reentry_register=True,
    ...
)
```

This will make sure the plugin's entry points are registered by the `reentry` plugin manager when installed with `pip`.
If another install method is used, the same can be achieved by running `reentry scan` from the command line after installing the plugin python package.

### LINKED ISSUE #702: Plugin docs should have a download link to sample `setup.py`

### LINKED ISSUE #808: Update documentation to create virtualenv with --python parameter
Now virtualenv creates new env with latest python release (3.x) and AiiDA is not compatible with python 3.x yet. In documentation, update the line to create virtualenv for --python parameter:
E.g. virtualenv --python=/usr/bin/python2.7 ~/aiidapy

### PR DESCRIPTION
**Pull request by sphuber**
I have copied this PR from #818 because it had a merge conflict that I need to solve locally.

This is a significant reorganisation of the plugin developer documentation, taking advantage of the fact that we now have a plugin template that developers can simply copy to get started.

There are also a few changes to the user guide:
* Installation guide split into separate files
* Added page on installing aiida plugins

There is still something left to be done, namely to update the existing developer plugin tutorials and to structure them around the existing plugin template.
This is again a significant effort and I suggest this should be done in another pull request.

* fix #702 
* fix #701 
* fix #808

### CODE REVIEW

**Comment by ltalirz** [comment]
@sphuber I just tried checking out this branch and I'm no longer able to build the documentation:

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.5.2

Exception occurred:
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 176, in check_schema_version
    get_current_profile())
ConfigurationError: The code schema version is 1.0.7, but the version stored in the database (DbSetting table) is 1.0.5, stopping.
To migrate to latest version, go to aiida.backends.djsite and run:
verdi daemon stop
 python manage.py --aiida-profile=test_release migrate
The full traceback has been saved in /var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/sphinx-err-ARdgGI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
(aiida_ltal) leopold@b126028:~/Applications/aiida_ltalirz/docs
$ verdi daemon stop
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_ltal/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1043, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/verdilib.py", line 1028, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/baseclass.py", line 190, in run
    function_to_call(*args[1:])
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/cmdline/commands/daemon.py", line 236, in daemon_stop
    load_dbenv(process='daemon')
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/utils.py", line 79, in load_dbenv
    process=process, profile=profile, *args, **kwargs)
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 28, in load_dbenv
    check_schema_version()
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/backends/djsite/utils.py", line 176, in check_schema_version
    get_current_profile())
aiida.common.exceptions.ConfigurationError: The code schema version is 1.0.7, but the version stored in the database (DbSetting table) is 1.0.5, stopping.
To migrate to latest version, go to aiida.backends.djsite and run:
verdi daemon stop
 python manage.py --aiida-profile=test_release migrate
```

Note: The same command still works at commit dff7e1420ab2be165a0513dae2ef0999459873aa in release_v0.10.0, so this problem was introduced by some of the commits after that

**Comment by sphuber** [comment]
This is because the `release_v0.10.0` now contains the merged `fix_export_import` branch, which removed the `DbPath` table and so there are migrations. The reason it fails is that the database of your default profile is not yet updated. If you run the command that is given in the error message `python manage.py --aiida-profile=test_release migrate` from the `aiida/backends/djsite` directory, then it should work

**Comment by ltalirz** [comment]
First of all thanks for taking the time to merge the changes in the individual documents!

There is still a warning when I compile the docs that I would like to remove (plus one small fix). Can you give me write access to your fork for today?

Regarding the error message, I will open a separate issue.

**Comment by sphuber** [comment]
I have sent you a collaborator invite to get push rights to my fork

**Comment by sphuber** [comment]
I have fixed the error message for the incompatible database versions, but I am not sure what needs to be fixed related to the `verdi daemon stop` problem. For me the command works fine, even though the database needs to be migrated.

**Comment by ltalirz** [comment]
That is strange... 
After the migration, `verdi daemon stop` works again for me. Perhaps we can simply change the order and do `verdi daemon restart` after the db migration?
I guess it's still not safe though if the daemon keeps running during the migration...

**Comment by sphuber** [comment]
Yeah, I think that was the original thinking to have the daemon stop just to make sure that the database is not being accessed during migration. I will hold on with the merge until @giovannipizzi has taken a look at it then

**Comment by sphuber** [comment]
I think I just understood your earlier message about the daemon being fixed after the migration. That is what we would expect. Any of the daemon verdi commands will run `load_dbenv` and therefore the schema version check will be done. That also means for `verdi daemon stop`. So even though technically before migrating we need to stop the daemon, we can't... Really what users should be doing is to stop the daemon before updating their code base, but I am not sure where we can put this. Also not sure how we should change the error message when database version should be migrated, because I am not sure that we can make `verdi daemon stop` independent of the database environment, which would be the best solution.

**Comment by ltalirz** [comment]
you've dismissed my review, so I can't review again ;-)
anyhow, I just tested copy-pasting the path on another profile and it works fine

**Comment by sphuber** [comment]
That happened automatically somehow. Anyway, I have added you again, so you should be able to approve it now

**Pull request merged**
