### PR TITLE
docs: add note on increasing work_mem

### LINKED ISSUE #2859: profiling the daemon
In aiida-core 0.12 we noticed that running a few 100 calculations of a particular workflow led to very high CPU usage, almost exclusively spent inside Postgres.

Could you please suggest a way to profile what is going on, i.e. to figure out which queries are causing this and where in the python code they are originating from?

Mentioning @sphuber and @giovannipizzi  for comment
@danieleongari and @kjappelbaum for notice

### PR DESCRIPTION
**Pull request by ltalirz**
fix #2859 

 * add note on increasing work_mem
 * restructure troubleshooting section a bit

### CODE REVIEW

**Comment by ltalirz** [comment]
thanks for the suggestions - I've tried to incorporate them
in order not to overcomplicate things I don't include instructions for tuning the value depending on the size of the table but I think it contains everything needed to get started debugging

**Comment by ltalirz** [comment]
@sphuber do you have any idea why the tests failed? Seems to be exactly the same error as in #2420

It was thought that this could be prevented by adding the
`--no-cache-dir` argument to pip here: #2799
but perhaps that was fortuitous?

I also tried resetting the travis cache...

**Comment by sphuber** [comment]
It does seem to be the same error, and indeed the `--no-cache-dir` did consistently fix the problem last time. Maybe now there is an incompatibility even when installing everything from scratch, i.e. the version of `pymatgen` that we tell to install, will automatically install a version of `numpy` and `scipy` that are incompatible.

**Comment by ltalirz** [comment]
I'm going to merge this now... will hopefully fix this travis problem at some point as well.

**Pull request merged**
