### PR TITLE
Added node label in the tree end point response

### PR DESCRIPTION
**Pull request by waychal**
Added missing node label in the response of rest api tree endpoint.

### CODE REVIEW

**Comment by ltalirz** [comment]
Could you perhaps add one test?
Or is accessing the nodelabel already tested?

**Comment by waychal** [comment]
@ltalirz there is test available for tree endpoint. We do not specifically check the information passed for every node or edge.

**Comment by ltalirz** [comment]
> We do not specifically check the information passed for every node or edge.

Perhaps we could change this situation? ;-)

Does not have to be entirely exhaustive but checking at least once for each key that the expected value is returned would seem reasonable, no?

**Comment by waychal** [comment]
I have updated the test where the important attributes displayed for node in front end are checked in response json data.

**Pull request merged**
