### PR TITLE
Reorganization of some top level modules

### LINKED ISSUE #2311: Harmonization of aiida.common, aiida.control, aiida.manage, aiida.tools, aiida.utils
There are currently a number of top-level folders in aiida, whose meaning is not well defined:

* aiida.common
* aiida.control
* aiida.manage
* aiida.tools
* aiida.utils

This leads to confusion among new developers, and has also led to different interpretations of previous developers. We should 

 1. decide what these top-level folders should contain
 2. document this in the `__init__.py` of the corresponding folders
 3. move code that is currently in the wrong place to where it belongs

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #2311 

There are a few top-level modules whose purpose was not fully clear and
partially as well as partially overlapping, which caused the content to
be quite unorganized and scattered. Here we reorganize these modules
after having clearly defined their purpose:

 * aiida.common: for generic utility functions and data structures
 * aiida.manage: for code that manages an AiiDA instance
 * aiida.tools: for code that interfaces with third-party libraries

The module `aiida.control` has been removed. Code that interacted with
internal components have been moved into `cmdline` or `manage` where
applicable. The `aiida.control.postgres` has been moved to the
`aiida.manage.external` module which is reserved for code that have to
interact with system wide components, such as the postgres database.

The module `aiida.utils` has been removed. Generic functionality has
been placed in `aiida.common` and more specific functionality has been
placed in the appropriate sub folders.

### CODE REVIEW

**Comment by sphuber** [comment]
The only two things not done yet, are the `aiida.common.utils.Prettifier` class and its related functions, and the `aiida.common.orbital` module. The latter, together with `OrbitalData` and `ProjectionData` are too specific for `aiida-core` and should be probably be moved to `aiida-materials-science` plugin. We could do move it to `aiida-quantumespresso` for the time being, but I am not sure if other plugins also use it.

**Comment by ltalirz** [comment]
Wow, thanks a lot @sphuber ! 
I'll look through this tomorrow, ok?

**Comment by sphuber** [comment]
@giovannipizzi agreed on the `OrbitalData` and `ProjectionData`, but is the `aiida.common.orbital` module really necessary in `aiida-core`. As far as I can tell it only defines `RealHydrogenOrbital` as a subclass of `Orbital`, but it is not used anywhere. Is this used in wannier90? I see that `aiida-quantumespresso` uses these classes in the `projwfc` parser

**Comment by ltalirz** [comment]
>  Is there already a wiki page or somethings similar explaining what the folders are for?

We now documented the intended content of the folders in the respective `__init__.py`s.
I think that's already a big step; one could reuse these docstrings via automodule to have them also in the documentation, somewhere near the forward compatibility guarantees  #2313

**Pull request merged**
