### PR TITLE
improve error message for missing parse method

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by sphuber** [comment]
Would it perhaps be better to make `Parser` a proper abstract class and the `parse` method an abstract method. This would make the instantiation of a parser that does not implement `parse` raise a `TypeError`. I imagine this will also simplify the work for issue #2673

**Comment by ltalirz** [comment]
That seems like the right thing to do.

Will the error message include the fact that the "parse" method is not implemented?
 (rather than just `NotImplemented` as currently)

Anyhow, unless you want to do it immediately, we can also merge this first - whatever you prefer.

**Comment by sphuber** [comment]
This will be the error message
```
In [3]: p = Parser(node)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-d17a4041a4f2> in <module>()
----> 1 p = Parser(node)

TypeError: Can't instantiate abstract class Parser with abstract methods parse
```

**Comment by ltalirz** [comment]
Ok. It's perhaps not the clearest message but `parse` is in there.

It's also good that it is raised already when the parser is instantiated rather then only when the (missing) method is called.

**Comment by ltalirz** [comment]
closing in favor of #2693

**Pull request closed without merging**
